# Achtung: Passwörter für MinIO müssen mindestens 8 Zeichen lang sein!
# Dieses Secret setzt überall das Passwort "TestTest321!" (Base64-codiert)
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: minio
type: Opaque
data:
  rootUser: dGltb3Vy              # timour
  rootPassword: VGVzdFRlc3QzMjEh  # TestTest321!
  lokiPassword: VGVzdFRlc3QzMjEh  # TestTest321!
  tempoPassword: VGVzdFRlc3QzMjEh # TestTest321!