apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: minio
spec:
  interval: 1h
  chart:
    spec:
      chart: minio
      version: "5.0.15"
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: minio
  values:
    existingSecret: minio-secret
    drivesPerNode: 1
    replicas: 3
    pools: 1

    # Affinity für Raspberry Pi Cluster (arm64)
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/arch
              operator: In
              values:
              - arm64

    # Alternative: MinIO auf allen Nodes erlauben (Affinity entfernen oder auskommentieren)
    # affinity:
    #   {}

    persistence:
      enabled: true
      storageClass: longhorn
      accessMode: ReadWriteOnce
      size: 10Gi
    resources:
      requests:
        memory: 1Gi
    metrics:
      serviceMonitor:
        enabled: true
        includeNode: true
    buckets:
      - name: k3s-loki
        policy: none
      - name: k3s-tempo
        policy: none
    policies:
      - name: loki
        statements:
          - resources:
              - 'arn:aws:s3:::k3s-loki'
              - 'arn:aws:s3:::k3s-loki/*'
            actions:
              - "s3:DeleteObject"
              - "s3:GetObject"
              - "s3:ListBucket"
              - "s3:PutObject"
      - name: tempo
        statements:
          - resources:
              - 'arn:aws:s3:::k3s-tempo'
              - 'arn:aws:s3:::k3s-tempo/*'
            actions:
              - "s3:DeleteObject"
              - "s3:GetObject"
              - "s3:ListBucket"
              - "s3:PutObject"
              - "s3:GetObjectTagging"
              - "s3:PutObjectTagging"
    users:
      - accessKey: loki
        existingSecret: minio-secret
        existingSecretKey: lokiPassword
        policy: loki
      - accessKey: tempo
        existingSecret: minio-secret
        existingSecretKey: tempoPassword
        policy: tempo
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - www.timourhomelabminio.de
      tls:
        - secretName: minio-tls
          hosts:
            - www.timourhomelabminio.de
      path: /
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-issuer
        cert-manager.io/common-name: www.timourhomelabminio.de
    consoleIngress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - www.timourhomelabminio.de
      tls:
        - secretName: minio-console-tls
          hosts:
            - www.timourhomelabminio.de
      path: /
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-issuer
        cert-manager.io/common-name: www.timourhomelabminio.de