apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: linkding-db-production
  namespace: linkding
spec:
  description: Postgres database cluster for linkding (Production)
  imageName: ghcr.io/cloudnative-pg/postgresql:16.6-30-bookworm
  instances: 3 # mehr replicas für production

  inheritedMetadata:
    labels:
      app: linkding-database
      environment: production

  bootstrap:
    initdb:
      database: linkding
      owner: linkding

  monitoring:
    enablePodMonitor: true

  storage:
    size: 5Gi # Größeres Speichervolumen für Produktion
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      storageClassName: local-path

  backup:
    barmanObjectStore:
      destinationPath: "s3://piclusterhomelab/linkding-production/"
      s3Credentials:
        accessKeyId:
          name: aws-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: aws-creds
          key: ACCESS_SECRET_KEY
    retentionPolicy: 30d # Längere Aufbewahrungszeit für Backups
