apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: community-operator
  namespace: mongodb
spec:
  releaseName: community-operator
  chart:
    spec:
      chart: community-operator
      sourceRef:
        kind: HelmRepository
        name: mongodb
        namespace: flux-system
      version: "*"
  interval: 1h
  values:
    operator:
      watchNamespace: "*"
      nodeSelector:
        kubernetes.io/hostname: p3