# Pi optimierte Konfiguration für Cilium 1.16.6
kubeProxyReplacement: false # Verwenden Sie 'false' statt 'partial'
k8sServiceHost: "192.168.68.53"
k8sServicePort: 6443
# NodePort aktivieren
nodePort:
  enabled: true
# Ressourcenlimits für Raspberry Pi
operator:
  replicas: 1
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
# CNI-Konfiguration für k3s
cni:
  install: true
# Container Runtime Integration - aktualisiert für v1.16
socketPath: "/run/k3s/containerd/containerd.sock"
# BPF Features - deaktiviert für bessere Stabilität auf Pi
bpf:
  masquerade: false
# Routing-Modus für 1.16+
routingMode: "tunnel"
tunnelProtocol: "vxlan"
# Diese Zeile hilft bei der Initialisierung
nodeinit:
  enabled: true
# Hubble mit reduzierten Ressourcen für Pi
hubble:
  enabled: true
  relay:
    enabled: true
    resources:
      limits:
        cpu: 50m
        memory: 64Mi
      requests:
        cpu: 20m
        memory: 32Mi
  ui:
    enabled: true
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi
# Globale Ressourcenlimits für Cilium-Pods
resources:
  limits:
    cpu: 200m
    memory: 300Mi
  requests:
    cpu: 100m
    memory: 200Mi
