apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-cluster
  namespace: cnpg-system
spec:
  instances: 2 # von 1 auf 2 geändert
  imageName: ghcr.io/enterprisedb/postgresql:16.1
  storage:
    size: 1Gi
