---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flux-system
  namespace: flux-system
spec:
  values:
    global:
      extraArgs:
        - --timeout=10m
    sourceController:
      resources:
        limits:
          cpu: 200m
          memory: 512Mi
        requests:
          cpu: 50m
          memory: 64Mi
      env:
        - name: GOGC
          value: "20"
        - name: GOMAXPROCS
          value: "1"
    kustomizeController:
      resources:
        limits:
          cpu: 200m
          memory: 512Mi
        requests:
          cpu: 50m
          memory: 64Mi
      env:
        - name: GOGC
          value: "20"
        - name: GOMAXPROCS
          value: "1"
