hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: true
    service:
      type: ClusterIP
    resources:
      limits:
        cpu: 50m
        memory: 64Mi
      requests:
        cpu: 20m
        memory: 32Mi
