apiVersion: v1
kind: Secret
metadata:
  name: sops-age
  namespace: flux-system
stringData:
  age.agekey: |
    # created: 2025-02-03T14:13:36+01:00
    # public key: age10ysfmeczf9rvgd6alaqe4ffna3wm7s78y9wkysargvd7fxaq5u4s8gru2g
    AGE-SECRET-KEY-19X39UDJ4Q0UMQSEQ36XVUVXURLF76CRNGJZ2XSW8E4U0RFDE79ASUEEVGN
