apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: velero-aws-credentials
  namespace: velero
  annotations:
    force-sync: "true"
    reconcile.external-secrets.io/verbose-logging: "true"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: velero-aws-credentials
    creationPolicy: Owner
    template:
      # Format die Daten im korrekten Format für Velero
      data:
        cloud: |
          [default]
          aws_access_key_id={{ .aws_access_key_id }}
          aws_secret_access_key={{ .aws_secret_access_key }}
  data:
    - secretKey: aws_access_key_id
      remoteRef:
        key: picluster/velero-credentials
        property: aws_access_key_id
    - secretKey: aws_secret_access_key
      remoteRef:
        key: picluster/velero-credentials
        property: aws_secret_access_key
