apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 15m
  chart:
    spec:
      chart: velero
      version: "5.0.2"
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: velero
  values:
    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.8.0
        volumeMounts:
          - mountPath: /target
            name: plugins

    # Native AWS S3 configuration - NO MinIO settings
    configuration:
      provider: aws
      backupStorageLocation:
        name: default
        provider: aws
        default: true
        bucket: piclusterhomelab
        config:
          region: eu-central-1
          # NO s3ForcePathStyle
          # NO s3Url
          # NO insecureSkipTLSVerify

    credentials:
      existingSecret: velero-aws-credentials

    snapshotsEnabled: false

    # Add deployment specific settings to workaround template errors
    deployRestic: false
    metrics:
      enabled: true

    resources:
      requests:
        cpu: "100m"
        memory: "200Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
