apiVersion: v1
kind: Secret
metadata:
  name: velero-aws-credentials
  namespace: velero
type: Opaque
stringData:
  cloud: |
    [default]
    aws_access_key_id = timour
    aws_secret_access_key = 2206
    region = eu-central-1
