apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: daily-backup
  namespace: velero
spec:
  schedule: "0 3 * * *" # Daily at 3 AM
  template:
    includedNamespaces:
      - "*"
    includedResources:
      - "*"
    includeClusterResources: true
    ttl: 720h # 30 days retention
