apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
  - aws-credentials.yaml
  # Comment out the schedule for now - add it after Velero is running
  # - backup-schedule.yaml
