apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - repository.yaml
  - aws-credentials.yaml
  - release.yaml
  # Add this later once Velero is running:
  # - volumesnapshotclass.yaml
  # - schedule.yaml
