apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 15m
  timeout: 15m
  releaseName: velero
  chart:
    spec:
      chart: velero
      version: "12.13.3" # Aktuelle Version des Bitnami-Charts
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: velero
  install:
    createNamespace: true
    remediation:
      retries: 3
  values:
    # Bitnami Chart Struktur (unterschiedlich zu VMware Tanzu Chart)
    image:
      repository: bitnami/velero
      tag: 1.14.0 # Aktuelle Velero Version

    credentials:
      existingSecret: velero-aws-credentials
      useSecret: true

    configuration:
      provider: aws
      backupStorageLocation:
        name: default
        provider: aws
        bucket: piclusterhomelab
        config:
          region: eu-central-1

    # AWS Plugin (Bitnami-Format)
    plugins:
      aws:
        enabled: true

    # Ressourcen
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi

    # CSI Unterstützung später einschalten
    snapshotsEnabled: false
