apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 15m
  timeout: 10m
  chart:
    spec:
      chart: velero
      version: "3.1.0"
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: velero
  install:
    createNamespace: false
    remediation:
      retries: 3
  values:
    # Use ARM64-compatible image with Alpine base
    image:
      repository: velero/velero
      tag: v1.10.2-alpine

    # Use ARM64-compatible plugin
    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.6.0-arm64
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins

    # AWS config
    configuration:
      provider: aws
      backupStorageLocation:
        name: default
        provider: aws
        bucket: piclusterhomelab
        config:
          region: eu-central-1

    credentials:
      useSecret: true
      existingSecret: velero-aws-credentials

    # Disable features that might cause issues initially
    deployNodeAgent: false
    snapshotsEnabled: false

    # Target worker node with 16GB RAM
    nodeSelector:
      kubernetes.io/hostname: p3

    # Resource limits for ARM
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "256Mi"
