apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 15m
  timeout: 10m
  releaseName: velero
  chart:
    spec:
      chart: velero
      version: "4.0.3" # Downgrade to a known stable version
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: velero
  install:
    createNamespace: false # namespace already exists
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    # Plugin for AWS
    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.6.0
        volumeMounts:
          - mountPath: /target
            name: plugins

    # AWS S3 configuration - simplified
    configuration:
      provider: aws
      backupStorageLocation:
        name: default
        default: true
        provider: aws
        bucket: piclusterhomelab
        config:
          region: eu-central-1

    # Credentials from secret
    credentials:
      existingSecret: velero-aws-credentials
      useSecret: true

    # Disable volume snapshots initially
    snapshotsEnabled: false

    # Explicitly disable problematic features
    deployRestic: false

    # Resources for ARM architecture
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
