apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 15m
  timeout: 10m
  releaseName: velero
  chart:
    spec:
      chart: velero
      version: "4.0.3" # Keep this version
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: velero
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    configuration:
      provider: aws
      backupStorageLocation:
        bucket: piclusterhomelab
        config:
          region: eu-central-1
      # --- Add this section ---
      # Provide a minimal VolumeSnapshotLocation even if snapshotsEnabled is false
      # This might satisfy the template logic causing the NOTES.txt error.
      volumeSnapshotLocation:
        - name: aws-dummy-vsl # Give it a name
          provider: aws # Use the same provider as BSL or a non-CSI one
          config: {} # Empty config might be enough
      # --- End of added section ---

    credentials:
      useSecret: true
      existingSecret: velero-aws-credentials

    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.6.0
        volumeMounts:
          - mountPath: /target
            name: plugins

    # Snapshots remain disabled globally
    snapshotsEnabled: false
    deployRestic: false

    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi

    image:
      repository: velero/velero
      tag: v1.11.1

    serviceAccount:
      server:
        create: true
        name: velero
