apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 15m
  timeout: 10m
  chart:
    spec:
      # Use latest chart version that supports Velero 1.16.0
      chart: velero
      version: "5.1.6" # Updated chart version
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: velero
  install:
    createNamespace: false
    remediation:
      retries: 3
    # Skip CRDs to avoid upgrade issues
    skipCRDs: true
  upgrade:
    skipCRDs: true
  values:
    # Use latest Velero image
    image:
      repository: velero/velero
      tag: v1.16.0 # Latest version

    # Updated plugin version compatible with 1.16.0
    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.8.0
        volumeMounts:
          - mountPath: /target
            name: plugins

    # AWS configuration remains the same
    configuration:
      provider: aws
      backupStorageLocation:
        name: default
        provider: aws
        bucket: piclusterhomelab
        config:
          region: eu-central-1

    credentials:
      useSecret: true
      existingSecret: velero-aws-credentials

    # Start with minimal features
    deployNodeAgent: false
    snapshotsEnabled: false

    # Keep resource limits appropriate for Pi
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "256Mi"
