apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 15m
  chart:
    spec:
      chart: velero
      version: "2.7.0" # Older chart with better ARM compatibility
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: velero
  install:
    createNamespace: false
    remediation:
      retries: 3
  values:
    # Use v1.6.3 which has better ARM support
    image:
      repository: velero/velero
      tag: v1.6.3

    # Use matching plugin version
    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.2.0
        volumeMounts:
          - mountPath: /target
            name: plugins

    # Basic configuration
    configuration:
      provider: aws
      backupStorageLocation:
        name: default
        bucket: piclusterhomelab
        config:
          region: eu-central-1

    credentials:
      useSecret: true
      existingSecret: velero-aws-credentials

    # Target your 16GB RAM node
    nodeSelector:
      kubernetes.io/hostname: p3

    # Conservative resource settings
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "256Mi"
