apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 15m
  chart:
    spec:
      chart: velero
      version: "5.0.2"
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: velero
  values:
    # AWS backend plugin configuration
    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.10.0
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins

    # Storage configuration - for native AWS S3
    configuration:
      provider: aws
      features: EnableCSI
      backupStorageLocation:
        name: default
        provider: aws
        default: true
        bucket: piclusterhomelab
        config:
          region: eu-central-1
          # Remove MinIO specific settings:
          # s3ForcePathStyle: true
          # s3Url: https://minio.timourhomelab.org
          # insecureSkipTLSVerify: true

    # Use existing secret
    credentials:
      existingSecret: velero-aws-credentials

    # Disable VolumeSnapshotLocation CRD - not needed for CSI
    snapshotsEnabled: false

    # Reasonable resources for Pi cluster
    resources:
      requests:
        cpu: "100m"
        memory: "200Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"

    # Disable metrics collection until needed
    metrics:
      enabled: false
      serviceMonitor:
        enabled: false
