apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 15m
  chart:
    spec:
      chart: velero
      version: "5.0.2"
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: velero
  install:
    skipCRDs: false
    remediation:
      retries: 3
  values:
    # Required AWS plugin
    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.10.0
        volumeMounts:
          - mountPath: /target
            name: plugins

    # Minimal configuration
    configuration:
      provider: aws
      backupStorageLocation:
        name: default
        bucket: piclusterhomelab
        config:
          region: eu-central-1
          s3Url: "https://s3.eu-central-1.amazonaws.com"

    # Use credentials secret
    credentials:
      existingSecret: velero-aws-credentials

    # Disable snapshots initially
    snapshotsEnabled: false

    # Fix for ARM architecture
    nodeAgent:
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "200m"
          memory: "256Mi"
