apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 15m
  timeout: 10m
  releaseName: velero
  chart:
    spec:
      chart: velero
      # --- Change chart version ---
      version: "5.0.0"
      # --- End change ---
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: velero
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    configuration:
      provider: aws
      backupStorageLocation:
        bucket: piclusterhomelab
        config:
          region: eu-central-1
      # Keep the dummy VSL for now
      volumeSnapshotLocation:
        - name: aws-dummy-vsl
          provider: aws
          config: {}

    credentials:
      useSecret: true
      existingSecret: velero-aws-credentials

    initContainers:
      - name: velero-plugin-for-aws
        # --- Update plugin version for Velero v1.12.x ---
        image: velero/velero-plugin-for-aws:v1.8.0
        # --- End change ---
        volumeMounts:
          - mountPath: /target
            name: plugins

    snapshotsEnabled: false
    deployRestic: false

    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi

    image:
      repository: velero/velero
      # --- Update Velero image tag for chart 5.0.0 ---
      tag: v1.12.0
      # --- End change ---

    serviceAccount:
      server:
        create: true
        name: velero
