apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 15m
  chart:
    spec:
      chart: velero
      version: "2.32.6" # Older but more ARM-compatible version
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: velero
  install:
    createNamespace: false
    remediation:
      retries: 3
  values:
    # Use an older Velero version known to work on ARM64
    image:
      repository: velero/velero
      tag: v1.6.3 # Better ARM64 compatibility

    # Use matching AWS plugin
    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.2.0
        volumeMounts:
          - mountPath: /target
            name: plugins

    # Simplify storage location config
    configuration:
      provider: aws
      backupStorageLocation:
        name: default
        bucket: piclusterhomelab
        config:
          region: eu-central-1

    # Use existing secret
    credentials:
      useSecret: true
      existingSecret: velero-aws-credentials

    # Target p3 node with 16GB RAM
    nodeSelector:
      kubernetes.io/hostname: p3 # Your high-RAM node based on README

    # Disable features not needed initially
    deployRestic: false # Avoid additional components
    snapshotsEnabled: false # Enable later once basic backup is working

    # Resource limits for Raspberry Pi
    resources:
      requests:
        cpu: "50m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "256Mi"
