apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 15m
  releaseName: velero
  chart:
    spec:
      chart: velero
      version: "3.1.0" # Ältere, stabilere Version
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: velero
  install:
    createNamespace: true
    remediation:
      retries: 3
  values:
    # AWS S3 Konfiguration
    credentials:
      useSecret: true
      existingSecret: velero-aws-credentials # Von ExternalSecret erstellt

    configuration:
      provider: aws
      backupStorageLocation:
        provider: aws
        bucket: piclusterhomelab # Dein S3-Bucket
        config:
          region: eu-central-1 # Deine AWS-Region
          # KEINE Konfiguration für MinIO nötig (s3ForcePathStyle, s3Url)

    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.6.0
        volumeMounts:
          - mountPath: /target
            name: plugins

    # Verzichte zunächst auf CSI-Integration (füge später hinzu)
    snapshotsEnabled: false

    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
