apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 15m
  timeout: 10m
  chart:
    spec:
      chart: velero
      version: "3.1.0" # This version works better on ARM
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: velero
  install:
    createNamespace: false
    remediation:
      retries: 3
  values:
    # Resource limits for ARM
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "256Mi"

    # Ensure ARM compatibility
    image:
      repository: velero/velero
      tag: v1.10.2

    # Use AWS plugin that works on ARM
    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.6.0
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins

    # More compatible AWS config format
    configuration:
      # Avoid array-related errors
      provider: aws
      # Format as a simple object to avoid array-related errors
      backupStorageLocation:
        name: default
        provider: aws
        bucket: piclusterhomelab
        config:
          region: eu-central-1

    # Credentials from your external secret
    credentials:
      useSecret: true
      existingSecret: velero-aws-credentials

    # Disable features that might cause issues initially
    deployNodeAgent: false
    snapshotsEnabled: false

    # Target worker node with 16GB RAM
    nodeSelector:
      kubernetes.io/hostname: p3

    # Set low resource requests for restic if enabled later
    nodeAgent:
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "200m"
          memory: "256Mi"
