apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 15m
  timeout: 15m
  releaseName: velero
  chart:
    spec:
      chart: velero
      version: "7.1.1" # Bitnami Chart Version
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: velero
  install:
    createNamespace: true
    remediation:
      retries: 3
  values:
    image:
      repository: bitnami/velero
      tag: 1.13.0-debian-11-r10 # ARM-kompatible Version

    # AWS Konfiguration
    configuration:
      provider: aws
      backupStorageLocation:
        name: default
        provider: aws
        bucket: piclusterhomelab
        config:
          region: eu-central-1

    # Credentials
    credentials:
      secretContents:
        cloud: |
          [default]
          aws_access_key_id=timour
          aws_secret_access_key=2206

    # AWS Plugin
    plugins:
      aws:
        enabled: true

    # Ressourcen
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
