apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 15m
  timeout: 15m
  releaseName: velero
  chart:
    spec:
      chart: velero
      version: "3.1.0"
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: velero
  install:
    createNamespace: true
    remediation:
      retries: 3
    skipCRDs: true # Um den problematischen Job zu umgehen
  upgrade:
    skipCRDs: true
  values:
    # ARM-kompatibles Image verwenden
    image:
      repository: velero/velero
      # Standard-Image sollte multi-arch sein und ARM unterstützen
      tag: v1.12.0

    # AWS-Konfiguration
    configuration:
      provider: aws
      backupStorageLocation:
        provider: aws
        bucket: piclusterhomelab
        config:
          region: eu-central-1

    # Secret aus External Secret
    credentials:
      existingSecret: velero-aws-credentials
      useSecret: true

    # AWS-Plugin (multi-arch)
    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.8.0
        volumeMounts:
          - mountPath: /target
            name: plugins

    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi

    # CSI zunächst deaktiviert
    snapshotsEnabled: false
