apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 15m
  timeout: 10m
  releaseName: velero
  chart:
    spec:
      chart: velero
      version: "7.2.23" # Bitnami Chart Version (Beispiel)
      sourceRef:
        kind: HelmRepository
        name: bitnami # Name des Bitnami Repos
        namespace: velero # Oder flux-system
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  # --- Update Values für Bitnami Chart & AWS S3 ---
  values:
    # --- Credentials ---
    credentials:
      useSecret: true
      # --- Point to AWS credentials secret ---
      existingSecret: velero-aws-credentials # Dein AWS Secret Name
      # --- End change ---

    # --- Backup Storage Location (AWS S3) ---
    configuration:
      provider: aws
      backupStorageLocation:
        name: default
        # --- Dein AWS S3 Bucket Name ---
        bucket: piclusterhomelab # <--- EINGEFÜGT
        provider: aws
        config:
          # --- Deine AWS Region ---
          region: eu-central-1 # <--- EINGEFÜGT
          # --- s3ForcePathStyle und s3Url werden für AWS S3 nicht benötigt ---
          # s3ForcePathStyle: "true" # Entfernt
          # s3Url: <your-minio-s3-url> # Entfernt
          # insecureSkipTLSVerify: "true" # Entfernt (normalerweise nicht für AWS S3 benötigt)
          # --- End changes ---

      # --- Volume Snapshot Location (für CSI) ---
      # Bleibt gleich, da es sich auf Longhorn bezieht
      volumeSnapshotLocation:
        name: default-longhorn-backup
        provider: velero.io/csi
        config:
          volumeSnapshotClassName: velero-longhorn-backup-vsc # Dein VSC Name

    # --- Plugins ---
    # AWS Plugin wird weiterhin benötigt
    plugins:
      aws:
        enabled: true
        image:
          repository: velero/velero-plugin-for-aws
          tag: v1.8.2 # Passend zu Velero v1.12.x
          pullPolicy: IfNotPresent

    # --- CSI Integration ---
    # Bleibt gleich
    extraEnvVars:
      - name: VELERO_SCRATCH_DIR
        value: /tmp/velero
      - name: VELERO_FEATURES
        value: EnableCSI

    snapshotsEnabled: true # Snapshots aktivieren

    # --- Velero Image (Bitnami) ---
    # Bleibt gleich
    image:
      repository: bitnami/velero
      tag: 1.12.2 # Passend zur Chart Version 7.2.23

    # --- Service Account ---
    # Bleibt gleich
    serviceAccount:
      server:
        create: true

    # --- Restic ---
    # Bleibt gleich
    deployNodeAgent: false

    # --- Resource Limits ---
    # Bleibt gleich
    resources:
      requests:
        memory: 128Mi
        cpu: 100m
      limits:
        memory: 256Mi
        cpu: 200m
  # --- End Values Update ---
