apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: velero # Wie in der Doku empfohlen
spec:
  interval: 15m
  timeout: 10m
  releaseName: velero
  chart:
    spec:
      chart: velero
      # --- Neuere Chart-Version passend zur Doku/Plugins ---
      version: "6.1.0"
      sourceRef:
        kind: HelmRepository
        # --- Stelle sicher, dass dieses Repo existiert ---
        name: vmware-tanzu
        namespace: velero # Oder flux-system
      # --- End changes ---
  install:
    createNamespace: true # Sicherstellen, dass Namespace existiert
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  # --- Values angepasst an Doku & deine Anforderungen ---
  values:
    # --- Credentials via Secret (GitOps-freundlich) ---
    credentials:
      useSecret: true
      # --- Name deines MinIO Secrets ---
      existingSecret: velero-minio-credentials

    # --- Konfiguration ---
    configuration:
      provider: aws # Bleibt 'aws' für S3-kompatibel
      # --- Backup Storage Location (MinIO im Container) ---
      # Neuere Charts erwarten eine Liste
      backupStorageLocation:
        - name: default # Name der Location
          provider: aws # Provider innerhalb der Location
          # --- Dein MinIO Bucket ---
          bucket: <dein-minio-bucket-name> # z.B. k3s-velero
          config:
            region: minio # Platzhalter-Region für MinIO
            s3ForcePathStyle: "true"
            # --- URL zu deinem lokalen MinIO Container ---
            # z.B. http://192.168.1.100:9000 (IP deines Hosts)
            # oder http://minio-service.minio-ns:9000 (falls als K8s Service)
            s3Url: http://<minio-ip-oder-service-name>:<minio-port>
            # --- Wichtig für lokalen MinIO (HTTP/Self-Signed) ---
            insecureSkipTLSVerify: "true"
            # caCert: <base64-ca-cert> # Nur nötig bei Custom CA

      # --- Volume Snapshot Location (CSI für Longhorn) ---
      # Neuere Charts erwarten eine Liste
      volumeSnapshotLocation:
        - name: default-longhorn-backup # Name der Location
          provider: velero.io/csi # Korrekter Provider für CSI
          config:
            # --- Muss mit deiner VSC übereinstimmen ---
            volumeSnapshotClassName: velero-longhorn-backup-vsc

    # --- Features: CSI aktivieren ---
    features: EnableCSI

    # --- Plugins: AWS (für MinIO) UND CSI ---
    initContainers:
      - name: velero-plugin-for-aws
        # --- Version aus Doku ---
        image: velero/velero-plugin-for-aws:v1.10.0
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins
      # --- CSI Plugin HINZUGEFÜGT ---
      - name: velero-plugin-for-csi
        # --- Kompatible Version zu Velero v1.14.0 ---
        image: velero/velero-plugin-for-csi:v0.7.1
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins

    # --- Snapshots aktivieren (WICHTIG für CSI) ---
    # Entgegen der Doku MUSS dies true sein für CSI Snapshots
    snapshotsEnabled: true

    # --- Velero Image passend zum Chart 6.1.0 ---
    image:
      repository: velero/velero
      tag: v1.14.0

    # --- Restic/Node Agent deaktivieren (wie in Doku bevorzugt) ---
    # Name kann je nach Chart-Version variieren (deployRestic/deployNodeAgent)
    deployNodeAgent: false

    # --- Service Account ---
    serviceAccount:
      server:
        create: true

    # --- Ressourcen (Anpassen nach Bedarf) ---
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
  # --- End Values ---
