apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 15m
  timeout: 15m # Timeout erhöht
  releaseName: velero
  chart:
    spec:
      chart: velero
      version: "3.1.0"
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: velero
  install:
    createNamespace: true
    skipCRDs: true # CRD-Installation überspringen
    remediation:
      retries: 3
  upgrade:
    skipCRDs: true # Auch bei Upgrades überspringen
    remediation:
      retries: 3
  values:
    # Bestehende Values beibehalten
    configuration:
      provider: aws
      backupStorageLocation:
        provider: aws
        bucket: piclusterhomelab
        config:
          region: eu-central-1
    credentials:
      existingSecret: velero-aws-credentials
      useSecret: true
    initContainers:
      - image: velero/velero-plugin-for-aws:v1.6.0
        name: velero-plugin-for-aws
        volumeMounts:
          - mountPath: /target
            name: plugins
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
    snapshotsEnabled: false
