apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 15m
  chart:
    spec:
      chart: velero
      version: "2.32.6"
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: velero
  install:
    createNamespace: false
    remediation:
      retries: 3
  values:
    # Main Velero configuration (keep this part)
    image:
      repository: velero/velero
      tag: v1.6.3

    # Disable the CRD upgrade job
    upgradeCRDs: false

    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.2.0
        volumeMounts:
          - mountPath: /target
            name: plugins

    # Keep the rest of your configuration...
    configuration:
      provider: aws
      backupStorageLocation:
        name: default
        bucket: piclusterhomelab
        config:
          region: eu-central-1

    credentials:
      useSecret: true
      existingSecret: velero-aws-credentials

    nodeSelector:
      kubernetes.io/hostname: p3

    deployRestic: false
    snapshotsEnabled: false

    resources:
      requests:
        cpu: "50m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "256Mi"
