apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 15m
  timeout: 10m
  releaseName: velero
  chart:
    spec:
      chart: velero
      version: "4.0.3" # Keep this version
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: velero
  # Remove the install.args and upgrade.args sections
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    # Minimal required values
    configuration:
      provider: aws
      backupStorageLocation:
        bucket: piclusterhomelab
        config:
          region: eu-central-1
          # s3Url: "https://s3.eu-central-1.amazonaws.com" # Often not needed for AWS provider

    # Credentials from secret
    credentials:
      useSecret: true # Keep this
      existingSecret: velero-aws-credentials # Ensure this secret exists and is correct

    # AWS Plugin Init Container (Essential)
    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.6.0 # Match plugin version
        volumeMounts:
          - mountPath: /target
            name: plugins

    # Disable features that might complicate templating
    snapshotsEnabled: false
    deployRestic: false

    # Keep resource settings for ARM
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi

    # Explicitly set image tag to match chart version expectation if needed
    image:
      repository: velero/velero
      tag: v1.11.1 # v1.11.1 corresponds to chart 4.0.3

    # Ensure service account exists or is created by the chart
    serviceAccount:
      server:
        create: true # Let the chart create it if it doesn't exist
        name: velero # Default name
