apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 15m
  chart:
    spec:
      chart: velero
      version: "2.32.6"
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: velero
  values:
    image:
      repository: velero/velero
      tag: v1.10.0  # Ältere, stabile Version für ARM64
    
    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.5.0
        volumeMounts:
          - mountPath: /target
            name: plugins
    
    configuration:
      provider: aws
      backupStorageLocation:
        name: default
        bucket: piclusterhomelab-velero 
        config:
          region: eu-central-1
          s3ForcePathStyle: "true"
    
    credentials:
      useSecret: true
      existingSecret: aws-credentials
    
    # Deaktiviere problematische Features
    snapshotsEnabled: false
    
    # Füge wichtige Umgebungsvariablen hinzu
    extraEnvVars:
      - name: VELERO_DISABLE_API_GROUP_VERSIONS_CHECK
        value: "true"
    
    nodeSelector:
      kubernetes.io/hostname: p3