apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keycloak
resources:
  - namespace.yaml
  - release.yaml  # Jetzt native K8s manifests statt Helm
  # - repository.yaml  # ← REMOVED: Nicht mehr nötig