---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak
  namespace: keycloak
spec:
  interval: 5m
  chart:
    spec:
      chart: keycloakx
      version: ">=7.0.0"
      sourceRef:
        kind: HelmRepository
        name: codecentric
        namespace: keycloak
      interval: 5m
  values:
    # ========================================
    # KEYCLOAK IMAGE & BASIC CONFIG
    # ========================================
    
    image:
      repository: quay.io/keycloak/keycloak
      tag: "26.0.7"

    # ========================================
    # DATABASE CONFIGURATION
    # ========================================
    
    database:
      vendor: h2-file  # Mit persistence
      hostname: ""
      port: ""
      database: ""
      username: ""
      password: ""

    # ========================================
    # HEALTH CHECKS (FIX)
    # ========================================
    
    # Fix Health Check Configuration
    http:
      relativePath: /health  # ← Korrekter Health Endpoint für KeycloakX

    # Probe Configuration
    livenessProbe:
      enabled: true
      httpGet:
        path: /health
        port: http
      initialDelaySeconds: 60  # ← Mehr Zeit für Startup
      timeoutSeconds: 5
      periodSeconds: 30
      failureThreshold: 3

    readinessProbe:
      enabled: true
      httpGet:
        path: /health/ready
        port: http
      initialDelaySeconds: 30
      timeoutSeconds: 5
      periodSeconds: 10
      failureThreshold: 3

    startupProbe:
      enabled: true
      httpGet:
        path: /health
        port: http
      initialDelaySeconds: 30  # ← Startup Zeit
      timeoutSeconds: 5
      periodSeconds: 10
      failureThreshold: 60  # ← 10 Minuten Startup Zeit

    # ========================================
    # ADMIN CONFIGURATION
    # ========================================
    
    auth:
      adminUser: admin

    # ========================================
    # RESOURCES & PERFORMANCE
    # ========================================
    
    resources:
      limits:
        memory: 1Gi
        cpu: 500m
      requests:
        memory: 512Mi
        cpu: 250m

    # ========================================
    # SERVICE CONFIGURATION
    # ========================================
    
    service:
      type: ClusterIP
      port: 8080  # ← Stelle sicher dass Port 8080 verwendet wird

    # ========================================
    # PERSISTENCE (MIT PVC)
    # ========================================
    
    # Volume Mounts für H2 File Database
    extraVolumes: |
      - name: keycloak-data
        persistentVolumeClaim:
          claimName: keycloak-data-pvc

    extraVolumeMounts: |
      - name: keycloak-data
        mountPath: /opt/keycloak/data
        subPath: keycloak

    # ========================================
    # SECURITY
    # ========================================
    
    serviceAccount:
      create: true

    podSecurityContext:
      fsGroup: 1000

    securityContext:
      runAsUser: 1000
      runAsNonRoot: true

    # Ingress (wird in staging überschrieben)
    ingress:
      enabled: false