---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak
  namespace: keycloak
spec:
  interval: 5m
  chart:
    spec:
      chart: keycloakx
      version: ">=7.0.0"
      sourceRef:
        kind: HelmRepository
        name: codecentric
        namespace: keycloak
      interval: 5m
  values:
    # ========================================
    # KEYCLOAK IMAGE & CONFIG
    # ========================================
    
    # Keycloak Image (Latest stable)
    image:
      repository: quay.io/keycloak/keycloak
      tag: "26.0.7"

    # ========================================
    # STARTUP ARGUMENTS (KeycloakX Format)
    # ========================================
    
    # Command override for KeycloakX chart
    command:
      - /opt/keycloak/bin/kc.sh
    args:
      - start-dev
      - --http-enabled=true
      - --http-port=8080
      - --hostname-strict=false
      - --hostname-strict-https=false
      - --proxy=edge
      - --health-enabled=true

    # ========================================
    # ADMIN USER (Environment Variables)
    # ========================================
    
    # Environment Variables (KeycloakX format)
    extraEnv:
      - name: KEYCLOAK_ADMIN
        value: "admin"
      - name: KEYCLOAK_ADMIN_PASSWORD
        value: "admin123"

    # ========================================
    # SERVICE CONFIGURATION
    # ========================================
    
    # Service settings
    http:
      port: 8080

    service:
      type: ClusterIP
      port: 8080

    # ========================================
    # HEALTH CHECKS (SIMPLIFIED)
    # ========================================
    
    # Remove complex health checks that cause template errors
    # livenessProbe: {}
    # readinessProbe: {}
    
    # Use default health checks from chart

    # ========================================
    # RESOURCES
    # ========================================
    
    # Resource Limits für Raspberry Pi
    resources:
      limits:
        memory: 1Gi
        cpu: 500m
      requests:
        memory: 512Mi
        cpu: 250m

    # ========================================
    # PERSISTENCE (OPTIONAL)
    # ========================================
    
    # Persistence settings (simplified)
    persistence:
      deployPostgres: false  # No PostgreSQL

    # ========================================
    # SECURITY & RBAC
    # ========================================
    
    # Service Account
    serviceAccount:
      create: true

    # RBAC
    rbac:
      create: true

    # Security Context (simplified)
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000

    podSecurityContext:
      fsGroup: 1000

    # ========================================
    # INGRESS (deaktiviert)
    # ========================================
    
    ingress:
      enabled: false

    # ========================================
    # REPLICAS
    # ========================================
    
    replicas: 1