---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak
  namespace: keycloak
spec:
  interval: 5m
  chart:
    spec:
      chart: keycloakx
      version: ">=7.0.0"
      sourceRef:
        kind: HelmRepository
        name: codecentric
        namespace: keycloak
      interval: 5m
  values:
    # ========================================
    # MINIMAL KEYCLOAK CONFIGURATION
    # ========================================
    
    # Keycloak Image
    image:
      repository: quay.io/keycloak/keycloak
      tag: "26.0.7"

    # ========================================
    # STARTUP & ADMIN CONFIG
    # ========================================
    
    # Start in development mode
    args:
      - start-dev
      - --http-enabled=true
      - --http-port=8080
      - --hostname-strict=false

    # Admin credentials (FIXED FORMAT)
    extraEnv:
      - name: KEYCLOAK_ADMIN
        value: "admin"
      - name: KEYCLOAK_ADMIN_PASSWORD
        value: "admin123"

    # ========================================
    # HTTP & SERVICE CONFIGURATION (FIXED!)
    # ========================================
    
    # HTTP Configuration
    http:
      port: 8080
      # Remove other http configs that cause issues

    # Service Configuration (FIXED PORT REFERENCES)
    service:
      type: ClusterIP
      httpPort: 8080  # Use httpPort instead of port
      
    # ========================================
    # HEALTH CHECKS (FIXED FORMAT)
    # ========================================
    
    # Health Checks (using proper YAML format, not pipe strings)
    startupProbe:
      httpGet:
        path: /health/ready
        port: http  # Use port name instead of number
      initialDelaySeconds: 30
      timeoutSeconds: 5
      failureThreshold: 60
      periodSeconds: 10

    livenessProbe:
      httpGet:
        path: /health/live
        port: http  # Use port name instead of number
      initialDelaySeconds: 60
      timeoutSeconds: 5

    readinessProbe:
      httpGet:
        path: /health/ready
        port: http  # Use port name instead of number
      initialDelaySeconds: 30
      timeoutSeconds: 5

    # ========================================
    # BASIC SETTINGS
    # ========================================

    # Resources
    resources:
      limits:
        memory: 1Gi
        cpu: 500m
      requests:
        memory: 512Mi
        cpu: 250m

    # Ingress disabled
    ingress:
      enabled: false

    # Replicas
    replicas: 1