---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak
  namespace: keycloak
spec:
  interval: 5m
  chart:
    spec:
      chart: keycloakx
      version: ">=7.0.0"
      sourceRef:
        kind: HelmRepository
        name: codecentric
        namespace: keycloak
      interval: 5m
  values:
    # ========================================
    # KEYCLOAK IMAGE & CONFIG
    # ========================================
    
    # Keycloak Image (Latest stable)
    image:
      repository: quay.io/keycloak/keycloak
      tag: "26.0.7"

    # ========================================
    # STARTUP CONFIGURATION (CRITICAL!)
    # ========================================
    
    # Keycloak Start Arguments (Development Mode)
    args:
      - start-dev
      - --http-enabled=true
      - --http-port=8080
      - --hostname-strict=false
      - --hostname-strict-https=false
      - --proxy=edge  # Important for NGINX proxy
      - --health-enabled=true

    # ========================================
    # DATABASE: H2 In-Memory (Einfachster Start)
    # ========================================
    
    # Database Configuration (H2 In-Memory)
    # Keine DB-Konfiguration nötig für H2-Memory

    # ========================================
    # ADMIN USER
    # ========================================
    
    # Admin User Configuration
    extraEnv: |
      - name: KEYCLOAK_ADMIN
        value: "admin"
      - name: KEYCLOAK_ADMIN_PASSWORD
        value: "admin123"  # Temporär für ersten Start

    # ========================================
    # NETWORKING & SERVICE
    # ========================================
    
    # Service Configuration
    service:
      type: ClusterIP
      httpPort: 8080

    # Health Checks
    livenessProbe:
      httpGet:
        path: /health/live
        port: 8080
      initialDelaySeconds: 90
      timeoutSeconds: 5

    readinessProbe:
      httpGet:
        path: /health/ready
        port: 8080
      initialDelaySeconds: 60
      timeoutSeconds: 5

    # ========================================
    # RESOURCES
    # ========================================
    
    # Resource Limits für Raspberry Pi
    resources:
      limits:
        memory: 1Gi
        cpu: 500m
      requests:
        memory: 512Mi
        cpu: 250m

    # ========================================
    # SECURITY & PERMISSIONS
    # ========================================
    
    # Pod Security Context
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000

    # Container Security Context
    securityContext:
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      runAsUser: 1000
      capabilities:
        drop:
        - ALL

    # Service Account
    serviceAccount:
      create: true

    # ========================================
    # INGRESS (deaktiviert für ersten Test)
    # ========================================
    
    ingress:
      enabled: false