---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak
  namespace: keycloak
spec:
  interval: 5m
  chart:
    spec:
      chart: keycloakx
      version: ">=7.0.0"
      sourceRef:
        kind: HelmRepository
        name: codecentric
        namespace: keycloak
      interval: 5m
  values:
    # ========================================
    # MINIMAL CONFIGURATION ONLY
    # ========================================
    
    # Keycloak Image
    image:
      repository: quay.io/keycloak/keycloak
      tag: "26.0.7"
    
    # Admin credentials
    extraEnv:
      - name: KEYCLOAK_ADMIN
        value: "admin"
      - name: KEYCLOAK_ADMIN_PASSWORD  
        value: "admin123"
    
    # Start in development mode
    args:
      - start-dev
      - --http-enabled=true
      - --http-port=8080
      - --hostname-strict=false
    
    # Basic settings
    replicas: 1
    
    # Disable ingress
    ingress:
      enabled: false