---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak
  namespace: keycloak
spec:
  interval: 5m
  chart:
    spec:
      chart: keycloakx
      version: ">=7.0.0"
      sourceRef:
        kind: HelmRepository
        name: codecentric
        namespace: keycloak
      interval: 5m
  values:
    # ========================================
    # MINIMAL KEYCLOAK CONFIGURATION
    # ========================================
    
    # Keycloak Image
    image:
      repository: quay.io/keycloak/keycloak
      tag: "26.0.7"

    # ========================================
    # STARTUP & ADMIN CONFIG
    # ========================================
    
    # Start in development mode
    args:
      - start-dev
      - --http-enabled=true
      - --http-port=8080
      - --hostname-strict=false

    # Admin credentials (STRING format für KeycloakX Chart!)
    extraEnv: |
      - name: KEYCLOAK_ADMIN
        value: "admin"
      - name: KEYCLOAK_ADMIN_PASSWORD
        value: "admin123"

    # ========================================
    # BASIC SETTINGS
    # ========================================
    
    # Service
    service:
      type: ClusterIP
      port: 8080

    # Resources
    resources:
      limits:
        memory: 1Gi
        cpu: 500m
      requests:
        memory: 512Mi
        cpu: 250m

    # Ingress disabled
    ingress:
      enabled: false

    # Replicas
    replicas: 1