---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak
  namespace: keycloak
spec:
  interval: 5m
  chart:
    spec:
      chart: keycloakx
      version: ">=7.0.0"
      sourceRef:
        kind: HelmRepository
        name: codecentric
        namespace: keycloak
      interval: 5m
  values:
    # ========================================
    # KEYCLOAK IMAGE & BASIC CONFIG
    # ========================================
    
    image:
      repository: quay.io/keycloak/keycloak
      tag: "26.0.7"

    # ========================================
    # KEYCLOAK STARTUP COMMANDS (FIX)
    # ========================================
    
    # Explicit start command f端r KeycloakX
    command:
      - /opt/keycloak/bin/kc.sh
    args:
      - start
      - --optimized  # Use optimized mode
      - --hostname-strict=false  # Allow flexible hostname
      - --proxy=edge  # Behind reverse proxy
      - --http-enabled=true  # Enable HTTP

    # ========================================
    # DATABASE CONFIGURATION
    # ========================================
    
    database:
      vendor: h2-file
      hostname: ""
      port: ""
      database: ""
      username: ""
      password: ""

    # ========================================
    # ADMIN CONFIGURATION
    # ========================================
    
    auth:
      adminUser: admin

    # Environment Variables f端r Keycloak
    extraEnv: |
      - name: KEYCLOAK_ADMIN
        value: admin
      - name: KEYCLOAK_ADMIN_PASSWORD
        valueFrom:
          secretKeyRef:
            name: keycloak-keycloakx
            key: admin-password
      - name: KC_DB
        value: "h2-file"
      - name: KC_DB_URL_PATH
        value: "/opt/keycloak/data/h2/keycloakdb"
      - name: KC_HTTP_ENABLED
        value: "true"
      - name: KC_HOSTNAME_STRICT
        value: "false"
      - name: KC_PROXY
        value: "edge"

    # ========================================
    # HEALTH CHECKS (SIMPLIFIED)
    # ========================================
    
    # Simplified Health Checks
    livenessProbe:
      enabled: true
      httpGet:
        path: /health
        port: 8080
      initialDelaySeconds: 120  # Mehr Zeit f端r H2 Setup
      timeoutSeconds: 10
      periodSeconds: 30
      failureThreshold: 5

    readinessProbe:
      enabled: true
      httpGet:
        path: /health/ready
        port: 8080
      initialDelaySeconds: 60
      timeoutSeconds: 10
      periodSeconds: 15
      failureThreshold: 5

    startupProbe:
      enabled: true
      httpGet:
        path: /health
        port: 8080
      initialDelaySeconds: 60
      timeoutSeconds: 10
      periodSeconds: 15
      failureThreshold: 40  # 10 Minuten startup time

    # ========================================
    # RESOURCES & PERFORMANCE
    # ========================================
    
    resources:
      limits:
        memory: 1Gi
        cpu: 500m
      requests:
        memory: 512Mi
        cpu: 250m

    # ========================================
    # SERVICE CONFIGURATION
    # ========================================
    
    service:
      type: ClusterIP
      port: 8080

    # ========================================
    # PERSISTENCE (MIT PVC)
    # ========================================
    
    extraVolumes: |
      - name: keycloak-data
        persistentVolumeClaim:
          claimName: keycloak-data-pvc

    extraVolumeMounts: |
      - name: keycloak-data
        mountPath: /opt/keycloak/data
        subPath: keycloak

    # ========================================
    # SECURITY
    # ========================================
    
    serviceAccount:
      create: true

    podSecurityContext:
      fsGroup: 1000

    securityContext:
      runAsUser: 1000
      runAsNonRoot: true

    # Ingress (wird in staging 端berschrieben)
    ingress:
      enabled: false

    # ========================================
    # CLOUDNATIVE-PG INTEGRATION (OPTIONAL - auskommentiert)
    # ========================================
    # Um CloudNativePG zu verwenden, uncomment diese Sektion:
    #
    # database:
    #   vendor: postgres
    #   hostname: "keycloak-db-staging-rw"
    #   port: 5432
    #   database: "keycloak"
    #   existingSecret: "keycloak-db-staging-app"
    #   existingSecretUserKey: "username"
    #   existingSecretPasswordKey: "password"
    #
    # # PostgreSQL Environment Variables
    # extraEnv: |
    #   - name: KC_DB
    #     value: "postgres"
    #   - name: KC_DB_URL_HOST
    #     value: "keycloak-db-staging-rw"
    #   - name: KC_DB_URL_PORT
    #     value: "5432"
    #   - name: KC_DB_URL_DATABASE
    #     value: "keycloak"
    #   - name: KC_DB_USERNAME
    #     valueFrom:
    #       secretKeyRef:
    #         name: keycloak-db-staging-app
    #         key: username
    #   - name: KC_DB_PASSWORD
    #     valueFrom:
    #       secretKeyRef:
    #         name: keycloak-db-staging-app
    #         key: password
    #   - name: KEYCLOAK_ADMIN
    #     value: admin
    #   - name: KEYCLOAK_ADMIN_PASSWORD
    #     valueFrom:
    #       secretKeyRef:
    #         name: keycloak-keycloakx
    #         key: admin-password
    #   - name: KC_HTTP_ENABLED
    #     value: "true"
    #   - name: KC_HOSTNAME_STRICT
    #     value: "false"
    #   - name: KC_PROXY
    #     value: "edge"
    #
    # # Remove H2 volumes for PostgreSQL
    # extraVolumes: ""
    # extraVolumeMounts: ""