---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app: keycloak
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/component: identity-provider
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
        app.kubernetes.io/name: keycloak
        app.kubernetes.io/component: identity-provider
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:26.0.7
        command:
        - /opt/keycloak/bin/kc.sh
        - start-dev
        - --http-enabled=true
        - --http-port=8080
        - --hostname-strict=false
        env:
        - name: KEYCLOAK_ADMIN
          value: admin
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: admin123  # TODO: Move to Secret in production
        ports:
        - name: http
          containerPort: 8080
        # Resources für Raspberry Pi
        resources:
          limits:
            memory: 1Gi
            cpu: 500m
          requests:
            memory: 512Mi
            cpu: 250m
        # NO HEALTH CHECKS - Let Keycloak start completely first
      # Service Account
      serviceAccountName: keycloak
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app: keycloak
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/component: identity-provider
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: http
    protocol: TCP
  selector:
    app: keycloak
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app: keycloak
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/component: identity-provider
automountServiceAccountToken: false