---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak
  namespace: keycloak
spec:
  interval: 5m
  chart:
    spec:
      chart: keycloakx
      version: ">=7.0.0"
      sourceRef:
        kind: HelmRepository
        name: codecentric
        namespace: keycloak
      interval: 5m
  values:
    # ========================================
    # MINIMAL KEYCLOAK CONFIGURATION
    # ========================================
    
    # Keycloak Image
    image:
      repository: quay.io/keycloak/keycloak
      tag: "26.0.7"

    # ========================================
    # DATABASE: In-Memory H2 (einfachste)
    # ========================================
    
    # H2 In-Memory Database (keine Persistence)
    database:
      vendor: h2-mem

    # ========================================
    # ADMIN USER
    # ========================================
    
    # Admin User
    auth:
      adminUser: admin
      # adminPassword wird automatisch generiert

    # ========================================
    # COMMAND OVERRIDE (explizit)
    # ========================================
    
    # Explizite Start-Command
    command:
      - /opt/keycloak/bin/kc.sh
    args:
      - start-dev
      - --http-enabled=true
      - --http-port=8080
      - --hostname-strict=false
      - --hostname-strict-https=false

    # ========================================
    # RESOURCES
    # ========================================
    
    resources:
      limits:
        memory: 1Gi
        cpu: 500m
      requests:
        memory: 512Mi
        cpu: 250m

    # ========================================
    # SERVICE
    # ========================================
    
    service:
      type: ClusterIP
      httpPort: 8080

    # ========================================
    # INGRESS (deaktiviert)
    # ========================================
    
    ingress:
      enabled: false

    # ========================================
    # SECURITY (minimal)
    # ========================================
    
    serviceAccount:
      create: true

    # ========================================
    # REMOVE ALL CUSTOM CONFIG
    # ========================================
    # Keine extraVolumes, extraVolumeMounts, custom persistence
    # Keine podSecurityContext, securityContext Overrides
    # Lass das Chart alles selbst handhaben