---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak
  namespace: keycloak
spec:
  interval: 5m
  chart:
    spec:
      chart: keycloakx
      version: ">=7.0.0"
      sourceRef:
        kind: HelmRepository
        name: codecentric
        namespace: keycloak
      interval: 5m
  values:
    # ========================================
    # KEYCLOAK IMAGE & BASIC CONFIG
    # ========================================
    
    image:
      repository: quay.io/keycloak/keycloak
      tag: "26.0.7"

    # ========================================
    # CHART-KOMPATIBLE KONFIGURATION
    # ========================================
    
    # Verwende Chart-eigene HTTP-Konfiguration (nicht überschreiben)
    http:
      # Let chart handle HTTP configuration
      relativePath: /auth  # Chart default

    # ========================================
    # DATABASE CONFIGURATION (SIMPLIFIED)
    # ========================================
    
    # H2 File Database (Chart-kompatibel)
    database:
      vendor: h2-file

    # ========================================
    # ADMIN CONFIGURATION
    # ========================================
    
    # Admin User (Chart-kompatible Syntax)
    auth:
      adminUser: admin

    # ========================================
    # RESOURCES & PERFORMANCE
    # ========================================
    
    resources:
      limits:
        memory: 1Gi
        cpu: 500m
      requests:
        memory: 512Mi
        cpu: 250m

    # ========================================
    # SERVICE CONFIGURATION
    # ========================================
    
    service:
      type: ClusterIP
      httpPort: 8080

    # ========================================
    # PERSISTENCE (MIT PVC)
    # ========================================
    
    # Chart-eigene Persistence
    persistence:
      deployPostgres: false  # Disable built-in PostgreSQL
      
    # Extra Volumes für H2 Database
    extraVolumes: |
      - name: keycloak-data
        persistentVolumeClaim:
          claimName: keycloak-data-pvc

    extraVolumeMounts: |
      - name: keycloak-data
        mountPath: /opt/keycloak/data
        subPath: keycloak

    # ========================================
    # SECURITY
    # ========================================
    
    serviceAccount:
      create: true

    podSecurityContext:
      fsGroup: 1000

    securityContext:
      runAsUser: 1000
      runAsNonRoot: true

    # ========================================
    # INGRESS (wird in staging überschrieben)
    # ========================================
    
    ingress:
      enabled: false

    # ========================================
    # REMOVE CUSTOM CONFIGURATION
    # ========================================
    # Entferne alle custom command/args/extraEnv/health checks
    # Lass das Chart seine eigenen Defaults verwenden

    # ========================================
    # CLOUDNATIVE-PG INTEGRATION (OPTIONAL - auskommentiert)
    # ========================================
    # Um CloudNativePG zu verwenden:
    #
    # database:
    #   vendor: postgres
    #   hostname: "keycloak-db-staging-rw"
    #   port: 5432
    #   database: "keycloak"
    #   existingSecret: "keycloak-db-staging-app"
    #   existingSecretUserKey: "username"
    #   existingSecretPasswordKey: "password"
    #
    # # Remove H2 volumes for PostgreSQL
    # extraVolumes: ""
    # extraVolumeMounts: ""