apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: efk
  namespace: elastic
spec:
  version: 8.15.0
  nodeSets:
  - name: default
    count: 1    # Ein Node f端r Test
    config:
      node.store.allow_mmap: false  # Wichtig f端r Raspberry Pi
    volumeClaimTemplates: 
      - metadata:
          name: elasticsearch-data
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
          storageClassName: longhorn  # Deine Storage Class
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          resources:
            requests:
              memory: 1Gi
              cpu: 500m
            limits:
              memory: 2Gi  # Angepasst f端r Raspberry Pi
              cpu: 1000m
  http:
    tls:
      selfSignedCertificate:
        disabled: true  # TLS deaktiviert f端r einfacheren Test