apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: elastic
spec:
  version: 8.15.0
  count: 1
  elasticsearchRef:
    name: "efk"  # Referenz zu Elasticsearch
  http:
    tls:
      selfSignedCertificate:
        disabled: true  # TLS deaktiviert für einfacheren Test
  podTemplate:
    spec:
      containers:
      - name: kibana
        resources:
          requests:
            memory: 512Mi
            cpu: 250m
          limits:
            memory: 1Gi
            cpu: 500m