apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: elastic
spec:
  version: 8.15.0
  count: 1
  elasticsearchRef:
    name: "efk"
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  podTemplate:
    spec:
      # Bevorzuge p3, aber kann auch auf p2 laufen
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values: ["p3"]
          - weight: 50
            preference:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values: ["p2"]
      containers:
      - name: kibana
        resources:
          requests:
            memory: 512Mi
            cpu: 150m
          limits:
            memory: 1Gi
            cpu: 300m









#apiVersion: kibana.k8s.elastic.co/v1
#kind: Kibana
#metadata:
 # name: kibana
 # namespace: elastic
#spec:
 # version: 8.15.0
  #count: 1
  #elasticsearchRef:
 #  name: "efk"  # Referenz zu Elasticsearch
  #http:
    #tls:
    #  selfSignedCertificate:
    #    disabled: true  # TLS deaktiviert für einfacheren Test
 # podTemplate:
  #  spec:
  #    containers:
 #     - name: kibana
 #       resources:
   #       requests:
   #         memory: 512Mi
   #         cpu: 250m
  #        limits:
   #         memory: 1Gi
    #        cpu: 500m