apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: eck-operator
  namespace: elastic-system
spec:
  interval: 5m
  chart:
    spec:
      chart: eck-operator
      version: 2.15.0
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: elastic-system
  values:
    # ECK Operator Konfiguration für Raspberry Pi
    installCRDs: true
    resources:
      limits:
        memory: 512Mi
        cpu: 100m
      requests:
        memory: 256Mi
        cpu: 100m