apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fluentd
  namespace: logging
spec:
  interval: 15m
  chart:
    spec:
      chart: fluentd
      version: "0.3.9"
      sourceRef:
        kind: HelmRepository
        name: fluent
        namespace: logging
  values:
    kind: DaemonSet

    # Run on all nodes
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule

    # Efficient resources
    resources:
      requests:
        cpu: 50m
        memory: 100Mi
      limits:
        cpu: 100m
        memory: 200Mi

    # Mount paths for logs
    extraVolumeMounts:
      - name: varlog
        mountPath: /var/log
      - name: varlibcontainerd
        mountPath: /var/lib/containerd/io.containerd.grpc.v1.cri/containers
        readOnly: true

    extraVolumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibcontainerd
        hostPath:
          path: /var/lib/containerd/io.containerd.grpc.v1.cri/containers

    # Security context for access permissions
    securityContext:
      privileged: true
      runAsUser: 0

    # Elasticsearch configuration
    env:
      - name: FLUENT_ELASTICSEARCH_HOST
        value: "elasticsearch-master"
      - name: FLUENT_ELASTICSEARCH_PORT
        value: "9200"
      - name: FLUENT_ELASTICSEARCH_SCHEME
        value: "http"

    # Custom Fluentd configuration
    configMapConfigs:
      fluent.conf: |-
        <source>
          @type tail
          path /var/log/containers/*.log
          pos_file /var/log/fluentd-containers.log.pos
          tag kubernetes.*
          read_from_head true
          <parse>
            @type json
            time_format %Y-%m-%dT%H:%M:%S.%NZ
            keep_time_key true
          </parse>
        </source>

        <filter kubernetes.**>
          @type kubernetes_metadata
        </filter>

        <match kubernetes.**>
          @type elasticsearch
          host elasticsearch-master
          port 9200
          logstash_format true
          logstash_prefix fluentd
          
          <buffer>
            @type file
            path /var/log/fluentd-buffer
            flush_mode interval
            flush_interval 5s
            chunk_limit_size 2M
            total_limit_size 512M
            flush_thread_count 2
          </buffer>
        </match>
