apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fluentd
  namespace: logging
spec:
  interval: 15m
  chart:
    spec:
      chart: fluentd
      version: "0.3.9"
      sourceRef:
        kind: HelmRepository
        name: fluent
        namespace: logging
  install:
    remediation:
      retries: 3
  values:
    kind: DaemonSet

    # Basic settings
    rbac:
      create: true
    livenessProbe: null
    readinessProbe: null
    nameOverride: fluentd-logging

    # Use very minimal resources
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 256Mi

    securityContext:
      privileged: true
      runAsUser: 0

    # Run on all nodes
    tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule

    # Mount logs
    extraVolumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers

    extraVolumeMounts:
      - name: varlog
        mountPath: /var/log
      - name: varlibdockercontainers
        mountPath: /var/lib/docker/containers
        readOnly: true

    configMapConfigs:
      fluent.conf: |-
        <system>
          log_level fatal
        </system>

        # Just collect logs from containers you care about, with no parsing
        <source>
          @type tail
          path /var/log/containers/*.log
          exclude_path ["/var/log/containers/*fluentd*", "/var/log/containers/*elastic*", "/var/log/containers/*logging*", "/var/log/containers/*kibana*"]
          pos_file /var/log/kubernetes.log.pos
          tag raw.kubernetes
          read_from_head true
          <parse>
            @type none
          </parse>
        </source>

        # Only if you want separate indices by namespace
        <match raw.kubernetes>
          @type rewrite_tag_filter
          <rule>
            key $.kubernetes.namespace_name
            pattern ^(.+)$
            tag $1
          </rule>
        </match>

        # Send to Elasticsearch with no further processing
        <match **>
          @type elasticsearch
          host elasticsearch-master
          port 9200
          scheme http
          user "#{ENV['FLUENT_ELASTICSEARCH_USER']}"
          password "#{ENV['FLUENT_ELASTICSEARCH_PASSWORD']}"
          index_name ${tag}
          
          <buffer>
            @type file
            path /var/log/fluentd-buffer
            flush_mode interval
            flush_interval 10s
            chunk_limit_size 2M
            total_limit_size 256M
            retry_max_interval 30
            retry_forever false
          </buffer>
        </match>

    plugins:
      - fluent-plugin-rewrite-tag-filter

    env:
      - name: FLUENT_ELASTICSEARCH_USER
        valueFrom:
          secretKeyRef:
            name: elasticsearch-credentials
            key: username
      - name: FLUENT_ELASTICSEARCH_PASSWORD
        valueFrom:
          secretKeyRef:
            name: elasticsearch-credentials
            key: password
      - name: FLUENT_LOG_LEVEL
        value: "fatal"
