apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: fluent
  namespace: logging
spec:
  interval: 1h
  url: https://fluent.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fluentd
  namespace: logging
spec:
  interval: 15m
  chart:
    spec:
      chart: fluentd
      version: "0.3.9"
      sourceRef:
        kind: HelmRepository
        name: fluent
        namespace: logging
  values:
    # Use a confirmed ARM-compatible image
    image:
      repository: fluent/fluentd-kubernetes-daemonset
      tag: "v1.14.6-debian-elasticsearch7-1.1"
      pullPolicy: IfNotPresent # Changed from Always to prevent rate limits

    # Single collector deployment
    kind: Deployment
    replicas: 1

    # Minimalist configuration
    podSecurityPolicy:
      enabled: false

    # Lower resource limits to ensure it runs
    resources:
      limits:
        cpu: 100m
        memory: 200Mi
      requests:
        cpu: 50m
        memory: 128Mi

    # Disable all optional features
    metrics:
      enabled: false
    autoscaling:
      enabled: false
    livenessProbe:
      enabled: false
    readinessProbe:
      enabled: false

    # Basic Elasticsearch output with minimal config
    configMaps:
      output.conf: |-
        <match **>
          @type elasticsearch
          host elasticsearch-master
          port 9200
          path ""
          scheme http
          ssl_verify false
          logstash_format true
          include_tag_key true
          buffer_type memory
          retry_limit 3
          flush_interval 30s
        </match>

      # Simplified input config
      input.conf: |-
        <source>
          @type tail
          path /var/log/containers/*.log
          pos_file /var/log/fluentd-containers.log.pos
          tag kubernetes.*
          <parse>
            @type json
          </parse>
        </source>
