apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fluentd
  namespace: logging
spec:
  interval: 15m
  chart:
    spec:
      chart: fluentd
      version: "0.3.9"
      sourceRef:
        kind: HelmRepository
        name: fluent
        namespace: logging
  install:
    remediation:
      retries: 3
  values:
    # Run as DaemonSet to collect logs from all nodes
    kind: DaemonSet

    # Completely disable Pod Security Policy
    rbac:
      create: true
      pspEnabled: false

    podSecurityPolicy:
      enabled: false

    # Skip PSP templates using nameOverride
    nameOverride: fluentd-logging

    # Disable health probes that are failing
    livenessProbe: null
    readinessProbe: null

    # Match the exact image version that's being used
    image:
      repository: fluent/fluentd-kubernetes-daemonset
      tag: "v1.14.6-debian-elasticsearch7-1.0"

    # Increase memory limits to prevent OOMKilled
    resources:
      requests:
        cpu: 50m
        memory: 200Mi
      limits:
        cpu: 200m
        memory: 512Mi

    # Fluentd buffer optimization to reduce memory usage
    configMapConfigs:
      system.conf: |-
        <system>
          root_dir /tmp/fluentd-buffers/
          <log>
            format json
            level info
          </log>
        </system>

      buffer.conf: |-
        <match **>
          @type elasticsearch
          host "#{ENV['FLUENT_ELASTICSEARCH_HOST']}"
          port "#{ENV['FLUENT_ELASTICSEARCH_PORT']}"
          scheme "#{ENV['FLUENT_ELASTICSEARCH_SCHEME'] || 'http'}"
          user "#{ENV['FLUENT_ELASTICSEARCH_USER'] || use_default}"
          password "#{ENV['FLUENT_ELASTICSEARCH_PASSWORD'] || use_default}"
          
          # Buffer settings to reduce memory usage
          <buffer>
            @type file
            path /var/log/fluentd-buffers/kubernetes.system.buffer
            flush_mode interval
            flush_interval 5s
            chunk_limit_size 2M
            queue_limit_length 8
            retry_max_interval 30
            retry_forever false
          </buffer>
        </match>

    # Connect to Elasticsearch
    env:
      - name: FLUENT_ELASTICSEARCH_HOST
        value: "elasticsearch-master"
      - name: FLUENT_ELASTICSEARCH_PORT
        value: "9200"
      - name: FLUENT_ELASTICSEARCH_SCHEME
        value: "http"
      - name: FLUENT_ELASTICSEARCH_USER
        valueFrom:
          secretKeyRef:
            name: elasticsearch-credentials
            key: username
      - name: FLUENT_ELASTICSEARCH_PASSWORD
        valueFrom:
          secretKeyRef:
            name: elasticsearch-credentials
            key: password

    # Allow running on all nodes
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
