apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fluentd
  namespace: logging
spec:
  interval: 15m
  chart:
    spec:
      chart: fluentd
      version: "0.3.9"
      sourceRef:
        kind: HelmRepository
        name: fluent
        namespace: logging
  install:
    remediation:
      retries: 3
  values:
    kind: DaemonSet

    rbac:
      create: true
      pspEnabled: false

    podSecurityPolicy:
      enabled: false

    livenessProbe: null
    readinessProbe: null

    nameOverride: fluentd-logging

    resources:
      requests:
        cpu: 100m
        memory: 300Mi
      limits:
        cpu: 300m
        memory: 600Mi

    securityContext:
      privileged: true
      runAsUser: 0

    tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule

    extraVolumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers

    extraVolumeMounts:
      - name: varlog
        mountPath: /var/log
      - name: varlibdockercontainers
        mountPath: /var/lib/docker/containers
        readOnly: true

    plugins:
      - fluent-plugin-kubernetes_metadata_filter

    configMapConfigs:
      fluent.conf: |-
        <system>
          log_level fatal
        </system>

        # Only collect application logs, exclude ALL logging infrastructure
        <source>
          @type tail
          path /var/log/containers/*.log
          exclude_path ["/var/log/containers/*fluentd*", "/var/log/containers/*logging*", "/var/log/containers/*elastic*", "/var/log/containers/*kibana*"]
          pos_file /var/log/kubernetes.log.pos
          tag kubernetes
          read_from_head true
          <parse>
            @type none
          </parse>
        </source>

        # Write directly to ES with simplest setup possible
        <match kubernetes>
          @type elasticsearch
          host "elasticsearch-master"
          port "9200"
          scheme "http"
          user "#{ENV['FLUENT_ELASTICSEARCH_USER']}"
          password "#{ENV['FLUENT_ELASTICSEARCH_PASSWORD']}"
          index_name "k8s-logs-#{Time.now.strftime('%Y.%m.%d')}"
          
          <buffer>
            @type file
            path /var/log/fluentd-buffer
            flush_mode interval
            flush_interval 5s
            chunk_limit_size 8M
            retry_max_interval 30
            retry_forever false
          </buffer>
        </match>

    env:
      - name: FLUENT_ELASTICSEARCH_USER
        valueFrom:
          secretKeyRef:
            name: elasticsearch-credentials
            key: username
      - name: FLUENT_ELASTICSEARCH_PASSWORD
        valueFrom:
          secretKeyRef:
            name: elasticsearch-credentials
            key: password
      - name: FLUENT_LOG_LEVEL
        value: "fatal"
