apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: logstash
  namespace: logging
spec:
  interval: 15m
  chart:
    spec:
      chart: logstash
      version: "7.17.3"
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: logging
  uninstall:
    keepHistory: false
  install:
    timeout: 10m
  values:
    # Use Deployment for simplicity
    kind: Deployment

    # Minimal resource requirements
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi

    # Simplified Java settings
    logstashJavaOpts: "-Xms128m -Xmx256m"

    # Disable persistence
    persistence:
      enabled: false

    # Use standard user (avoid privilege issues)
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000

    podSecurityContext:
      fsGroup: 1000
      runAsUser: 1000

    # Set up correct volume mapping
    extraVolumes:
      - name: logstash-temp
        emptyDir: {}

    extraVolumeMounts:
      - name: logstash-temp
        mountPath: /usr/share/logstash/data

    # Simple init container to prepare directories
    extraInitContainers:
      - name: init-permissions
        image: busybox:latest
        command: ["sh", "-c", "mkdir -p /tmp/data && chmod -R 777 /tmp/data"]
        volumeMounts:
          - name: logstash-temp
            mountPath: /tmp/data

    # Basic Logstash configuration
    logstashConfig:
      logstash.yml: |
        http.host: "0.0.0.0"
        path.data: /usr/share/logstash/data
        log.level: info
        pipeline.workers: 1

    # Minimal pipeline that should work
    logstashPipeline:
      logstash.conf: |
        input {
          http {
            port => 8080
          }
        }

        output {
          elasticsearch {
            hosts => ["elasticsearch-master:9200"]
            user => "${ELASTICSEARCH_USER}"
            password => "${ELASTICSEARCH_PASSWORD}"
            index => "logs-%{+YYYY.MM.dd}"
          }
        }

    # Authentication
    extraEnv:
      - name: ELASTICSEARCH_USER
        valueFrom:
          secretKeyRef:
            name: elasticsearch-credentials
            key: username
      - name: ELASTICSEARCH_PASSWORD
        valueFrom:
          secretKeyRef:
            name: elasticsearch-credentials
            key: password

    # Add the HTTP port to the service
    service:
      type: ClusterIP
      ports:
        - name: http-input
          port: 8080
          protocol: TCP
          targetPort: 8080
        - name: api
          port: 9600
          protocol: TCP
          targetPort: 9600
