apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fluentd
  namespace: logging
spec:
  interval: 15m
  chart:
    spec:
      chart: fluentd
      version: "0.3.9"
      sourceRef:
        kind: HelmRepository
        name: fluent
        namespace: logging
  values:
    kind: DaemonSet

    # Run on ALL nodes to collect logs
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule

    # Mount host paths for logs
    extraVolumeMounts:
      - name: varlog
        mountPath: /var/log
      - name: containerd-log
        mountPath: /var/lib/containerd/io.containerd.grpc.v1.cri/containers
        readOnly: true
      - name: varlibdockercontainers
        mountPath: /var/lib/docker/containers
        readOnly: true

    extraVolumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: containerd-log
        hostPath:
          path: /var/lib/containerd/io.containerd.grpc.v1.cri/containers
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers

    # Give proper permissions
    securityContext:
      privileged: true
      runAsUser: 0

    # Required plugins
    plugins:
      - fluent-plugin-kubernetes_metadata_filter

    # Resource requests appropriate for collector nodes
    resources:
      requests:
        cpu: 50m
        memory: 100Mi
      limits:
        cpu: 100m
        memory: 200Mi

    env:
      - name: FLUENT_ELASTICSEARCH_HOST
        value: "elasticsearch-master"
      - name: FLUENT_ELASTICSEARCH_PORT
        value: "9200"
      - name: FLUENT_ELASTICSEARCH_SCHEME
        value: "http"
      - name: FLUENT_LOG_LEVEL
        value: "info"

    # Configuration to forward logs to Elasticsearch
    configMapConfigs:
      fluent.conf: |-
        <source>
          @type tail
          path /var/log/containers/*.log
          pos_file /var/log/fluentd-containers.log.pos
          tag kubernetes.*
          read_from_head true
          <parse>
            @type json
            time_format %Y-%m-%dT%H:%M:%S.%NZ
            keep_time_key true
          </parse>
        </source>

        <filter kubernetes.**>
          @type kubernetes_metadata
        </filter>

        <match kubernetes.**>
          @type elasticsearch
          host elasticsearch-master
          port 9200
          index_name fluentd.${record["kubernetes"]["namespace_name"]}.%Y%m%d
          
          <buffer>
            @type file
            path /var/log/fluentd-buffer
            flush_mode interval
            flush_interval 5s
            flush_thread_count 4
            retry_max_interval 30
            chunk_limit_size 8M
            total_limit_size 1G
          </buffer>
        </match>
