apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: logstash
  namespace: logging
spec:
  interval: 15m
  chart:
    spec:
      chart: logstash
      version: "7.17.3"
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: logging
  install:
    remediation:
      retries: 3
  values:
    image: "docker.elastic.co/logstash/logstash"
    imageTag: "8.8.2"

    # Use DaemonSet for coverage on all nodes
    kind: DaemonSet

    logstashConfig:
      logstash.yml: |
        http.host: 0.0.0.0
        log.level: error
        config.reload.automatic: true

    # Pipeline configuration that will create logstash-logstash-pipeline ConfigMap
    logstashPipeline:
      logstash.conf: |
        input {
          file {
            path => ["/var/log/containers/*.log"]
            exclude => ["/var/log/containers/*logstash*", "/var/log/containers/*fluent*", "/var/log/containers/*elastic*"]
            sincedb_path => "/var/log/logstash/sincedb"
            codec => "json"
            type => "container"
          }
        }

        filter {
          # Skip logs with excessive backslashes to avoid recursion
          if [log] =~ /\\{4,}/ {
            drop {}
          }
          
          # Extract kubernetes metadata from the file path
          grok {
            match => { "path" => "/var/log/containers/%{DATA:pod_name}_%{DATA:namespace}_%{GREEDYDATA:container_name}\.log" }
          }
        }

        output {
          elasticsearch {
            hosts => ["elasticsearch-master:9200"]
            user => "${ELASTICSEARCH_USER}"
            password => "${ELASTICSEARCH_PASSWORD}"
            index => "k8s-logs-%{+YYYY.MM.dd}"
          }
        }

    extraEnvs:
      - name: ELASTICSEARCH_USER
        valueFrom:
          secretKeyRef:
            name: elasticsearch-credentials
            key: username
      - name: ELASTICSEARCH_PASSWORD
        valueFrom:
          secretKeyRef:
            name: elasticsearch-credentials
            key: password

    extraVolumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers

    extraVolumeMounts:
      - name: varlog
        mountPath: /var/log
      - name: varlibdockercontainers
        mountPath: /var/lib/docker/containers
        readOnly: true

    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi

    tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
