apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fluentd
  namespace: logging
spec:
  interval: 15m
  chart:
    spec:
      chart: fluentd
      version: "0.3.9"
      sourceRef:
        kind: HelmRepository
        name: fluent
        namespace: logging
  install:
    remediation:
      retries: 3
  values:
    kind: DaemonSet

    # Basic settings
    rbac:
      create: true
      pspEnabled: false
    podSecurityPolicy:
      enabled: false
    livenessProbe: null
    readinessProbe: null
    nameOverride: fluentd-logging

    resources:
      requests:
        cpu: 100m
        memory: 400Mi
      limits:
        cpu: 400m
        memory: 800Mi

    securityContext:
      privileged: true
      runAsUser: 0

    tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule

    extraVolumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers

    extraVolumeMounts:
      - name: varlog
        mountPath: /var/log
      - name: varlibdockercontainers
        mountPath: /var/lib/docker/containers
        readOnly: true

    plugins: []

    configMapConfigs:
      fluent.conf: |-
        <system>
          log_level fatal
        </system>

        # Use raw approach - no parsing at all
        <source>
          @type tail
          path /var/log/containers/*.log
          exclude_path [
            "/var/log/containers/*fluentd*",
            "/var/log/containers/*elastic*",
            "/var/log/containers/*logging*",
            "/var/log/containers/*kibana*"
          ]
          pos_file /var/log/kubernetes.log.pos
          tag k8s.*
          read_from_head true
          <parse>
            @type none
          </parse>
        </source>

        # Direct output to Elasticsearch with minimal processing
        <match k8s.**>
          @type elasticsearch
          host elasticsearch-master
          port 9200
          scheme http
          user "#{ENV['FLUENT_ELASTICSEARCH_USER']}"
          password "#{ENV['FLUENT_ELASTICSEARCH_PASSWORD']}"
          index_name k8s-rawlogs
          
          <buffer>
            @type file
            path /var/log/fluentd-buffer
            flush_mode interval
            flush_interval 5s
            flush_thread_count 1
            chunk_limit_size 8M
            retry_max_interval 30
            retry_forever false
          </buffer>
        </match>

    env:
      - name: FLUENT_ELASTICSEARCH_USER
        valueFrom:
          secretKeyRef:
            name: elasticsearch-credentials
            key: username
      - name: FLUENT_ELASTICSEARCH_PASSWORD
        valueFrom:
          secretKeyRef:
            name: elasticsearch-credentials
            key: password
      - name: FLUENT_LOG_LEVEL
        value: "fatal"
