# In homelabtm/pi-cluster/infrastructure/controllers/base/efk/fluentd/release.yaml
spec:
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: fluent # This must match the repository name
        namespace: logging
