apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: fluent
  namespace: logging
spec:
  interval: 1h
  url: https://fluent.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fluentd
  namespace: logging
spec:
  interval: 15m
  chart:
    spec:
      chart: fluentd
      version: "0.5.0"
      sourceRef:
        kind: HelmRepository
        name: fluent
        namespace: logging
  values:
    # Use ARM-compatible image
    image:
      repository: fluent/fluentd-kubernetes-daemonset
      tag: v1.16.2-debian-elasticsearch7-1.0-arm64

    # Run as a single deployment
    kind: Deployment
    replicas: 1

    # Disable resource-intensive features
    metrics:
      enabled: false # Disable metrics which are causing probe failures

    # Disable PodSecurityPolicy
    podSecurityPolicy:
      enabled: false

    # Reduced resource limits for Raspberry Pi
    resources:
      limits:
        cpu: 100m
        memory: 400Mi # Increase memory limit
      requests:
        cpu: 50m
        memory: 200Mi

    # Disable probes that were failing
    livenessProbe:
      enabled: false
    readinessProbe:
      enabled: false

    # Environment variables to tune memory usage
    env:
      - name: RUBY_GC_HEAP_OLDOBJECT_LIMIT_FACTOR
        value: "0.9"
      - name: FLUENT_ELASTICSEARCH_SED_DISABLE
        value: "true"

    # Elasticsearch output configuration
    configMaps:
      output.conf: |-
        <match **>
          @type elasticsearch
          host elasticsearch-master
          port 9200
          logstash_format true
          logstash_prefix fluentd
          include_tag_key true
          user elastic
          password changeme
          tag_key @log_name
          flush_interval 10s
          retry_limit 20
          retry_wait 5s
          buffer_chunk_limit 2M
          buffer_queue_limit 32
          overflow_action block
        </match>
