apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fluentd
  namespace: logging
spec:
  interval: 15m
  chart:
    spec:
      chart: fluentd
      version: "0.3.9"
      sourceRef:
        kind: HelmRepository
        name: fluent
        namespace: logging
  values:
    kind: DaemonSet

    # Disable PodSecurityPolicy for newer K8s
    podSecurityPolicy:
      enabled: false

    # Run on all nodes including control-plane
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule

    # Mount paths for logs
    extraVolumeMounts:
      - name: varlog
        mountPath: /var/log
      - name: containerd-log
        mountPath: /var/lib/containerd/io.containerd.grpc.v1.cri/containers
        readOnly: true

    extraVolumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: containerd-log
        hostPath:
          path: /var/lib/containerd/io.containerd.grpc.v1.cri/containers

    # Required permissions
    securityContext:
      privileged: true
      runAsUser: 0

    # Conservative resource settings for Pi
    resources:
      requests:
        cpu: 50m
        memory: 100Mi
      limits:
        cpu: 100m
        memory: 200Mi

    # Fluentd configuration to collect and forward logs
    configMapConfigs:
      fluent.conf: |-
        <source>
          @type tail
          path /var/log/containers/*.log
          pos_file /var/log/fluentd-containers.log.pos
          tag kubernetes.*
          read_from_head true
          <parse>
            @type json
            time_format %Y-%m-%dT%H:%M:%S.%NZ
          </parse>
        </source>

        <filter kubernetes.**>
          @type kubernetes_metadata
          skip_labels false
          skip_container_metadata false
          skip_namespace_metadata false
        </filter>

        <match kubernetes.**>
          @type elasticsearch
          host elasticsearch-master
          port 9200
          logstash_format true
          logstash_prefix fluentd
          <buffer>
            @type file
            path /var/log/fluentd-buffers
            flush_mode interval
            flush_interval 5s
            retry_max_interval 30
            chunk_limit_size 2M
            queue_limit_length 8
          </buffer>
        </match>
