apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fluentd
  namespace: logging
spec:
  interval: 15m
  chart:
    spec:
      chart: fluentd
      version: "0.3.9"
      sourceRef:
        kind: HelmRepository
        name: fluent
        namespace: logging
  values:
    image:
      repository: fluent/fluentd-kubernetes-daemonset
      tag: "v1.14.6-debian-elasticsearch7-1.1"
      pullPolicy: IfNotPresent

    # Change to DaemonSet for collecting logs from all nodes
    kind: DaemonSet

    # Disable problematic probes
    livenessProbe: null
    readinessProbe: null

    podSecurityPolicy:
      enabled: false

    metrics:
      enabled: false

    # Resources for Raspberry Pi
    resources:
      limits:
        cpu: 100m
        memory: 200Mi
      requests:
        cpu: 50m
        memory: 128Mi

    # Mount the secret for authentication
    extraVolumeMounts:
      - name: elastic-credentials
        mountPath: /etc/elastic-credentials
        readOnly: true

    extraVolumes:
      - name: elastic-credentials
        secret:
          secretName: elasticsearch-credentials

    # Set environment variables from the secret
    env:
      - name: ELASTICSEARCH_USERNAME
        valueFrom:
          secretKeyRef:
            name: elasticsearch-credentials
            key: username
      - name: ELASTICSEARCH_PASSWORD
        valueFrom:
          secretKeyRef:
            name: elasticsearch-credentials
            key: password
      - name: K8S_NODE_NAME
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName

    # Configure Elasticsearch with credentials from environment variables
    configMaps:
      output.conf: |-
        <match **>
          @type elasticsearch
          host elasticsearch-master
          port 9200
          scheme http
          logstash_format true
          include_tag_key true
          user "#{ENV['ELASTICSEARCH_USERNAME']}"
          password "#{ENV['ELASTICSEARCH_PASSWORD']}"
          <buffer>
            @type memory
            flush_interval 30s
            retry_limit 5
          </buffer>
        </match>

      input.conf: |-
        <source>
          @type tail
          path /var/log/containers/*.log
          pos_file /var/log/fluentd-containers.log.pos
          tag kubernetes.*
          <parse>
            @type json
          </parse>
        </source>
