# File: homelabtm/pi-cluster/infrastructure/controllers/base/efk/fluentd/release.yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fluentd
  namespace: logging
spec:
  interval: 15m
  chart:
    spec:
      chart: fluentd
      version: "0.3.9"
      sourceRef:
        kind: HelmRepository
        name: fluent
        namespace: logging
      interval: 1h
  values:
    image:
      repository: fluent/fluentd-kubernetes-daemonset
      tag: "v1.14.6-debian-elasticsearch7-1.1"
      pullPolicy: IfNotPresent

    # Make it run as DaemonSet to collect logs from all nodes
    kind: DaemonSet

    # Raspberry Pi resource limits
    resources:
      limits:
        cpu: 100m
        memory: 200Mi
      requests:
        cpu: 50m
        memory: 128Mi

    # Connect to Elasticsearch
    env:
      - name: FLUENT_ELASTICSEARCH_HOST
        value: "elasticsearch-master"
      - name: FLUENT_ELASTICSEARCH_PORT
        value: "9200"
      - name: FLUENT_ELASTICSEARCH_SCHEME
        value: "http"
      - name: FLUENT_ELASTICSEARCH_USER
        valueFrom:
          secretKeyRef:
            name: elasticsearch-credentials
            key: username
      - name: FLUENT_ELASTICSEARCH_PASSWORD
        valueFrom:
          secretKeyRef:
            name: elasticsearch-credentials
            key: password

    # Run on all nodes including control plane
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule

    # Disable problematic probes for Pi
    livenessProbe: null
    readinessProbe: null
