apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: fluent
  namespace: logging
spec:
  interval: 1h
  url: https://fluent.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fluentd
  namespace: logging
spec:
  interval: 15m
  chart:
    spec:
      chart: fluentd
      version: "0.3.9"
      sourceRef:
        kind: HelmRepository
        name: fluent
        namespace: logging
  values:
    # Basic configuration for ARM device
    image:
      repository: fluent/fluentd-kubernetes-daemonset
      tag: "v1.14.6-debian-elasticsearch7-1.1"
      pullPolicy: IfNotPresent

    # Run as normal deployment
    kind: Deployment
    replicas: 1

    # CRITICAL: Explicitly set probe configuration to null to override defaults
    livenessProbe: null
    readinessProbe: null

    # Disable security policy
    podSecurityPolicy:
      enabled: false

    # Completely disable metrics that are causing issues
    metrics:
      enabled: false
      serviceMonitor: false

    # Conservative resource limits
    resources:
      limits:
        cpu: 100m
        memory: 200Mi
      requests:
        cpu: 50m
        memory: 128Mi

    # Basic fluentd configuration
    configMaps:
      output.conf: |-
        <match **>
          @type elasticsearch
          host elasticsearch-master
          port 9200
          scheme http
          logstash_format true
          include_tag_key true
          # Modern format for buffer configuration
          <buffer>
            @type memory
            flush_interval 30s
            retry_limit 3
          </buffer>
        </match>

      input.conf: |-
        <source>
          @type tail
          path /var/log/containers/*.log
          pos_file /var/log/fluentd-containers.log.pos
          tag kubernetes.*
          <parse>
            @type json
          </parse>
        </source>
