apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana-agent-operator
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: grafana-agent-operator
      version: "0.2.9"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
  install:
    createNamespace: true
