apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fluent-bit
  namespace: fluent-bit
spec:
  interval: 5m
  chart:
    spec:
      chart: fluent-bit
      version: 0.47.0
      sourceRef:
        kind: HelmRepository
        name: fluent-bit
        namespace: fluent-bit
  values:
    kind: DaemonSet
    
    # ✅ ARM64-kompatibles Alpine Image
    image:
      repository: fluent/fluent-bit
      tag: 3.1.4-alpine
      pullPolicy: IfNotPresent
    
    # Host directories
    daemonSetVolumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: etcmachineid
        hostPath:
          path: /etc/machine-id
          type: File
    
    daemonSetVolumeMounts:
      - name: varlog
        mountPath: /var/log
      - name: etcmachineid
        mountPath: /etc/machine-id
        readOnly: true
    
    # ✅ Environment variables - DEAKTIVIERE jemalloc
    env:
      - name: FLUENT_AGGREGATOR_HOST
        value: fluentd.fluent.svc.cluster.local
      - name: FLUENT_AGGREGATOR_PORT
        value: "24224"
      - name: FLUENT_AGGREGATOR_SHARED_KEY
        valueFrom:
          secretKeyRef:
            name: fluent-bit-env-secret
            key: FLUENT_AGGREGATOR_SHARED_KEY
      - name: FLUENT_SELFHOSTNAME
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
      # ✅ WICHTIG: Deaktiviere jemalloc komplett
      - name: MALLOC_CONF
        value: "junk:false"
      - name: LD_PRELOAD
        value: ""
      - name: MALLOC_ARENA_MAX
        value: "1"
    
    # External configMap (wie im ricsanfre Tutorial)
    config: {}
    customParsers: {}
    existingConfigMap: fluent-bit-config
    
    # ✅ Command mit verbose logging
    command:
      - /fluent-bit/bin/fluent-bit
    args:
      - --workdir=/fluent-bit/etc
      - --config=/fluent-bit/etc/conf/fluent-bit.yaml
      - --verbose
    
    # Tolerations für control-plane
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
    
    # Init container
    initContainers:
      - name: init-fluentbit-directory
        image: busybox
        command: ['/bin/sh', '-c', 'if [ ! -d /var/log/fluentbit ]; then mkdir -p /var/log/fluentbit; fi ; if [ ! -d /var/log/fluentbit/tail-db ]; then mkdir -p /var/log/fluentbit/tail-db; fi ; if [ ! -d /var/log/fluentbit/storage ]; then mkdir -p /var/log/fluentbit/storage; fi']
        volumeMounts:
          - name: varlog
            mountPath: /var/log
    
    # ✅ Keine Hot-Reload (ARM64-Stabilität)
    hotReload:
      enabled: false
    
    # ARM64-optimierte Ressourcen
    resources:
      limits:
        memory: 128Mi
        cpu: 100m
      requests:
        memory: 64Mi
        cpu: 50m
    
    # ✅ Deaktiviere Health Probes temporär
    livenessProbe:
      enabled: false
    readinessProbe:
      enabled: false
    
    # Monitoring
    serviceMonitor:
      enabled: true
    
    # Dashboard
    dashboards:
      enabled: true
      labelKey: grafana_dashboard
      labelValue: 1
      annotations:
        grafana_folder: "Logging"