apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: elasticsearch
  namespace: efk-system
spec:
  interval: 15m
  chart:
    spec:
      chart: elasticsearch
      version: "8.13.4"
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: efk-system
  values:
    # Raspberry Pi optimized settings
    replicas: 1
    minimumMasterNodes: 1
    resources:
      requests:
        cpu: "200m"
        memory: "512Mi"
      limits:
        cpu: "1000m"
        memory: "1Gi"
    esJavaOpts: "-Xmx512m -Xms512m"
    persistence:
      enabled: true
      size: 5Gi
    antiAffinity: "soft"
