apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: filebeat
  namespace: filebeat
spec:
  interval: 5m
  chart:
    spec:
      chart: filebeat
      version: 8.5.1
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: filebeat
  values:
    daemonset:
      enabled: true
    nodeSelector:
      kubernetes.io/arch: arm64
    
    extraEnvs:
      - name: NODE_NAME
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
    
    filebeatConfig:
      filebeat.yml: |
        filebeat.inputs:
        - type: container
          paths:
            - /var/log/containers/*.log
          processors:
            - add_kubernetes_metadata:
                host: ${NODE_NAME}
                matchers:
                - logs_path:
                    logs_path: "/var/log/containers/"
        - type: log
          paths:
            - /var/log/auth.log
            - /var/log/syslog
          fields:
            log_type: system
          fields_under_root: true
        processors:
          - add_host_metadata:
              when.not.contains.tags: forwarded
          - add_docker_metadata: ~
          - add_kubernetes_metadata: ~
          - drop_event:
              when:
                or:
                  - contains:
                      kubernetes.pod.name: "filebeat"
                  - contains:
                      kubernetes.pod.name: "fluentd"
        # ✅ Output zu Fluentd (Port 5044 für Beats Input)
        output.logstash:
          hosts: ["fluentd.fluent.svc.cluster.local:5044"]
        logging.level: info
        logging.to_files: true
        logging.files:
          path: /var/log/filebeat
          name: filebeat
          keepfiles: 7
          permissions: 0644
    
    # ✅ KOMPLETT DEAKTIVIERE Elasticsearch-Integration
    elasticsearch:
      enabled: false
      host: ""
      port: ""
      username: ""
      password: ""
      protocol: ""
      
    # ✅ KOMPLETT DEAKTIVIERE Kibana-Integration  
    kibana:
      enabled: false
      host: ""
      port: ""
    
    # ✅ EXPLIZIT DEAKTIVIERE Secret-Mounts
    secretMounts: []
    
    # ✅ EXPLIZIT DEAKTIVIERE Default-Volumes
    extraVolumes: []
    extraVolumeMounts: []
    
    # ✅ EXPLIZIT DEAKTIVIERE Elasticsearch-Volumes
    elasticsearchHosts: []
    
    # ✅ EXPLIZIT DEAKTIVIERE SSL/TLS
    elasticsearchCertificateSecret: ""
    elasticsearchCertificateAuthoritiesFile: ""
    elasticsearchCertificateFile: ""
    elasticsearchKeyFile: ""
    
    # ✅ RBAC
    rbac:
      create: true
    
    clusterRoleRules:
      - apiGroups: [""]
        resources: ["nodes", "namespaces", "pods", "services", "endpoints", "events"]
        verbs: ["get", "list", "watch"]
      - apiGroups: ["apps"]
        resources: ["replicasets", "deployments", "daemonsets", "statefulsets"]
        verbs: ["get", "list", "watch"]
    
    resources:
      limits:
        memory: 200Mi
        cpu: 100m
      requests:
        memory: 100Mi
        cpu: 50m
    
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
    
    serviceMonitor:
      enabled: true
      labels:
        release: prometheus