apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: filebeat
  namespace: filebeat
spec:
  interval: 5m
  chart:
    spec:
      chart: filebeat
      version: 8.5.1
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: filebeat
  values:
    # ✅ ARM64-native Image
    image: "docker.elastic.co/beats/filebeat"
    imageTag: "8.5.1"
    imagePullPolicy: "IfNotPresent"
    
    # DaemonSet für jeden Node
    daemonset:
      enabled: true
      
    # ✅ ARM64 Node Selection
    nodeSelector:
      kubernetes.io/arch: arm64
    
    # Host-Verzeichnisse mounten
    extraVolumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: etcmachineid
        hostPath:
          path: /etc/machine-id
          type: File
    
    extraVolumeMounts:
      - name: varlog
        mountPath: /var/log
        readOnly: true
      - name: varlibdockercontainers
        mountPath: /var/lib/docker/containers
        readOnly: true
      - name: etcmachineid
        mountPath: /etc/machine-id
        readOnly: true
    
    # Environment Variables
    extraEnvs:
      - name: NODE_NAME
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
      - name: ELASTICSEARCH_HOST
        valueFrom:
          secretKeyRef:
            name: filebeat-env-secret
            key: ELASTICSEARCH_HOST
      - name: ELASTICSEARCH_PORT
        valueFrom:
          secretKeyRef:
            name: filebeat-env-secret
            key: ELASTICSEARCH_PORT
    
    # Externe Konfiguration
    filebeatConfig:
      filebeat.yml: |
        filebeat.inputs:
        # Kubernetes Container Logs
        - type: container
          paths:
            - /var/log/containers/*.log
          processors:
            - add_kubernetes_metadata:
                host: ${NODE_NAME}
                matchers:
                - logs_path:
                    logs_path: "/var/log/containers/"
        
        # System Logs
        - type: log
          paths:
            - /var/log/auth.log
            - /var/log/syslog
          fields:
            log_type: system
          fields_under_root: true
        
        # Processors
        processors:
          - add_host_metadata:
              when.not.contains.tags: forwarded
          - add_docker_metadata: ~
          - add_kubernetes_metadata: ~
          - drop_event:
              when:
                or:
                  - contains:
                      kubernetes.pod.name: "filebeat"
                  - contains:
                      kubernetes.pod.name: "fluentd"
        
        # Output zu Fluentd
        output.logstash:
          hosts: ["fluentd.fluent.svc.cluster.local:5044"]
          
        # Logging
        logging.level: info
        logging.to_files: true
        logging.files:
          path: /var/log/filebeat
          name: filebeat
          keepfiles: 7
          permissions: 0644
    
    # Tolerations für control-plane
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
    
    # ✅ ARM64-optimierte Ressourcen
    resources:
      limits:
        memory: 200Mi
        cpu: 100m
      requests:
        memory: 100Mi
        cpu: 50m
    
    # Security Context
    securityContext:
      runAsUser: 0
      privileged: false
      readOnlyRootFilesystem: false
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
    
    # Service Account
    serviceAccount:
      create: true
      name: filebeat
    
    # RBAC
    rbac:
      create: true
      
    # Monitoring
    serviceMonitor:
      enabled: true
      labels:
        release: prometheus