apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-credentials
  namespace: logging
type: Opaque
data:
  # Base64 encoded values for 'elastic' and '1qazXSW@3edc'
  username: ZWxhc3RpYw==
  password: MXFhelhTV0AzZWRj
  ELASTIC_PASSWORD: MXFhelhTV0AzZWRj
