apiVersion: v1
kind: Secret
metadata:
  name: elastic-credentials
  namespace: logging
type: Opaque
data:
  # These are base64-encoded values:
  # 'elastic' and '1qazXSW@3edc'
  username: ZWxhc3RpYw==
  password: MXFhelhTV0AzZWRj
