# File: homelabtm/pi-cluster/infrastructure/controllers/base/efk/repository.yaml
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: elastic
  namespace: logging
spec:
  interval: 1h
  url: https://helm.elastic.co
