apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  ### alertmanager , prometheusund grafana
  - kube-prometheus-stack
  - loki
    - promtail
    - grafana-agent

  ## grafana agent leitet logs und metrics an loki und prometheus weiter
