apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fluentd
  namespace: fluent
spec:
  interval: 5m
  chart:
    spec:
      chart: fluentd
      version: 0.5.3
      sourceRef:
        kind: HelmRepository
        name: fluent
        namespace: fluent
  values:
    # ✅ ARM64-kompatibles Image OHNE jemalloc
    image:
      repository: "fluent/fluentd-kubernetes-daemonset"
      tag: "v1.17.1-debian-elasticsearch8-arm64-1.0"
      pullPolicy: "IfNotPresent"

    # Deploy als Deployment
    kind: "Deployment"
    replicaCount: 1
    
    # Keine Service Account/RBAC
    serviceAccount:
      create: false
    rbac:
      create: false

    # Keine Log-Verzeichnisse mounten
    mountVarLogDirectory: false
    mountDockerContainersDirectory: false

    # ✅ ARM64-optimierte Umgebungsvariablen
    env:
      - name: FLUENT_ELASTICSEARCH_HOST
        value: "efk-es-http.elastic.svc.cluster.local"
      - name: FLUENT_ELASTICSEARCH_PORT
        value: "9200"
      - name: FLUENT_ELASTICSEARCH_USER
        valueFrom:
          secretKeyRef:
            name: fluentd-secrets
            key: es-username
      - name: FLUENT_ELASTICSEARCH_PASSWORD
        valueFrom:
          secretKeyRef:
            name: fluentd-secrets
            key: es-password
      - name: FLUENT_AGGREGATOR_SHARED_KEY
        valueFrom:
          secretKeyRef:
            name: fluentd-secrets
            key: fluentd-shared-key
      # ✅ WICHTIG: Disable jemalloc für ARM64
      - name: RUBY_GC_HEAP_GROWTH_FACTOR
        value: "1.1"
      - name: RUBY_GC_HEAP_GROWTH_MAX_SLOTS
        value: "10000"
      # ✅ Beats Input Port (für Filebeat)
      - name: FLUENTD_BEATS_BIND
        value: "0.0.0.0"
      - name: FLUENTD_BEATS_PORT
        value: "5044"

    # Externe Konfiguration
    mainConfigMapNameOverride: fluentd-main-config
    extraFilesConfigMapNameOverride: fluentd-extra-files

    # Template Volume
    volumes:
      - name: fluentd-es-template
        configMap:
          name: fluentd-es-template
          defaultMode: 0777

    volumeMounts:
      - name: fluentd-es-template
        mountPath: /etc/fluent/template

    # ✅ Service mit beiden Ports (Filebeat & Fluent Bit)
    service:
      type: "ClusterIP"
      ports:
      - name: forwarder
        protocol: TCP
        containerPort: 24224
        port: 24224
      - name: beats      # ✅ Für Filebeat
        protocol: TCP
        containerPort: 5044
        port: 5044

    # ✅ Plugins explizit installieren
    plugins:
      - fluent-plugin-elasticsearch
      - fluent-plugin-prometheus
      - fluent-plugin-beats    # ✅ Für Filebeat Input

    # ✅ ARM64-optimierte Ressourcen
    resources:
      limits:
        memory: 512Mi
        cpu: 200m
      requests:
        memory: 256Mi
        cpu: 100m

    # ✅ Deaktiviere Health Probes temporär
    livenessProbe:
      enabled: false
    readinessProbe:
      enabled: false

    # Node Affinity
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values: ["p3"]