apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fluentd
  namespace: fluent
spec:
  interval: 5m
  chart:
    spec:
      chart: fluentd
      version: 0.5.3
      sourceRef:
        kind: HelmRepository
        name: fluent
        namespace: fluent
  values:
    # Fluentd image
    image:
      repository: "fluent/fluentd"
      tag: "v1.17.1-debian-1.0"

    # Deploy als Deployment
    kind: "Deployment"
    replicaCount: 1
    
    # Keine Service Account/RBAC
    serviceAccount:
      create: false
    rbac:
      create: false

    # Keine Log-Verzeichnisse mounten
    mountVarLogDirectory: false
    mountDockerContainersDirectory: false

    # Elasticsearch Environment Variables
    env:
      - name: FLUENT_ELASTICSEARCH_HOST
        value: "efk-es-http.elastic.svc.cluster.local"
      - name: FLUENT_ELASTICSEARCH_PORT
        value: "9200"
      - name: FLUENT_ELASTICSEARCH_USER
        valueFrom:
          secretKeyRef:
            name: fluentd-secrets
            key: es-username
      - name: FLUENT_ELASTICSEARCH_PASSWORD
        valueFrom:
          secretKeyRef:
            name: fluentd-secrets
            key: es-password
      - name: FLUENT_AGGREGATOR_SHARED_KEY
        valueFrom:
          secretKeyRef:
            name: fluentd-secrets
            key: fluentd-shared-key

    # Externe Konfiguration verwenden
    mainConfigMapNameOverride: fluentd-main-config
    extraFilesConfigMapNameOverride: fluentd-extra-files

    # Template Volume
    volumes:
      - name: fluentd-es-template
        configMap:
          name: fluentd-es-template
          defaultMode: 0777

    volumeMounts:
      - name: fluentd-es-template
        mountPath: /etc/fluent/template

    # Service für Forwarder
    service:
      type: "ClusterIP"
      ports:
      - name: forwarder
        protocol: TCP
        containerPort: 24224

    # Plugins
    plugins:
      - fluent-plugin-elasticsearch
      - fluent-plugin-prometheus