apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: kube-system
data:
  traefik.yaml: |
    accessLog:
      format: json
      fields:
        defaultMode: keep
        names:
          RequestHost: keep
          RequestMethod: keep
          RequestPath: keep
          RequestProtocol: keep
          RequestScheme: keep
          ResponseCode: keep
          DownstreamStatus: keep
          DownstreamContentSize: keep
          RequestRefererHeader: keep
          RequestUserAgentHeader: keep
          RequestXForwardedForHeader: keep
          RequestXRealIpHeader: keep
          RequestXB3TraceIdHeader: keep
          RequestXB3SpanIdHeader: keep
        headers:
          defaultMode: keep
          names:
            X-B3-TraceId: keep
            X-B3-SpanId: keep
            X-B3-ParentSpanId: keep
            X-B3-Sampled: keep
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-dynamic-config
  namespace: kube-system
data:
  dynamic.yaml: |
    http:
      middlewares:
        tracing:
          headers:
            customRequestHeaders:
              X-B3-TraceId: ""
              X-B3-SpanId: ""
              X-B3-ParentSpanId: ""
              X-B3-Sampled: "1"
