apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kibana
  namespace: efk-system
spec:
  interval: 15m
  chart:
    spec:
      chart: kibana
      version: "8.13.4"
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: efk-system
  values:
    # Raspberry Pi optimized resources
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"

    elasticsearchHosts: "http://elasticsearch-master:9200"

    # Ingress configuration
    service:
      type: ClusterIP

    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      hosts:
        - host: kibana.timourhomelab.org
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: kibana-tls-secret
          hosts:
            - kibana.timourhomelab.org
