apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-config
  annotations:
    kustomize.toolkit.fluxcd.io/reconcile: disabled # Verhindert Konflikte
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: "" # Leerer String = Standard-StorageClass
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-metadata
  annotations:
    kustomize.toolkit.fluxcd.io/reconcile: disabled # Verhindert Konflikte
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: "" # Hinzufügen des leeren String
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-audiobooks
  annotations:
    kustomize.toolkit.fluxcd.io/reconcile: disabled # Verhindert Konflikte
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: "" # Hinzufügen des leeren String
