apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: cilium
      version: "1.16.x"  # Update to 1.16.x to match your working version
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: kube-system
  valuesFrom:
    - kind: ConfigMap
      name: cilium-values
      valuesKey: values.yaml
