# Pi optimierte Konfiguration
kubeProxyReplacement: "strict"
k8sServiceHost: "192.168.68.53" # IP des Master-Nodes
k8sServicePort: 6443

# Ressourcenlimits f端r Raspberry Pi
operator:
  replicas: 1
  resources:
    limits:
      cpu: 200m
      memory: 256Mi

# CNI-Konfiguration f端r k3s
cni:
  install: true

# Container Runtime Integration
containerRuntime:
  integration: "containerd"
  socketPath: "/run/k3s/containerd/containerd.sock"

# Performance f端r ARM
hostServices:
  enabled: true

# BPF Features
bpf:
  masquerade: true

# Hubble f端r Network Visibility (optional - kann deaktiviert werden)
hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: true
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
