# Working Cilium configuration for Raspberry Pi K3s cluster
kubeProxyReplacement: false
k8sServiceHost: "192.168.68.50"
k8sServicePort: 6443

# Resource limits for agent
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Networking settings
ipam:
  mode: "kubernetes"
tunnelProtocol: "vxlan"
bpf:
  masquerade: false

# CNI settings for k3s
cni:
  install: true
socketPath: "/run/k3s/containerd/containerd.sock"

# Resource settings for operator
operator:
  replicas: 1
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

# Hubble UI and metrics
hubble:
  enabled: true
  metrics:
    enabled:
      - drop
      - flow
      - tcp
  relay:
    enabled: true
    resources:
      limits:
        cpu: 50m
        memory: 64Mi
      requests:
        cpu: 20m
        memory: 32Mi
  ui:
    enabled: true
    resources:
      limits:
        cpu: 50m
        memory: 64Mi
      requests:
        cpu: 20m
        memory: 32Mi
    service:
      type: NodePort
      nodePort: 30100

# Allow running on all nodes
tolerations:
  - operator: Exists
