apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:vz8yzWm/Mk1OFzF7EkP1ej1foRWkn5aoGqbUIfJHdcxWaW+ZKbrER80NUU5pw+3SoawMT5476Z2mhHrzEBvSf5gdv3RcQrRg1ait0Ix3He7QfvaQJSFAqwPN9BxfDRMFOzLCs5bviaoWGeuyyZw3Glvm5vb6fY0tWbe9eY6wMyBhleF2LxhH88SFjbUehQYX55oc3wT4z9RyFT6rBxIQIDosfWqNpC8kLr1FFFiXg9Oe1t5jwGX+vRB983Rd4NooIhTOL1XMR+dK5qcZLnOzokub1yqAS+nQ,iv:b3YBxITwQfbvf7flyaWKfNuU6BItq7y5HIVVZyUkFRM=,tag:zQwS+ReYJQy6RPVcr39pIQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tunnel-credentials
    namespace: linkding
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10ysfmeczf9rvgd6alaqe4ffna3wm7s78y9wkysargvd7fxaq5u4s8gru2g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHSGZscGpkT1QrZmZhUDZ6
            ZTNWcXZTSFI4QVhnMUM2YVJSaUNKamFRcFZzClJrb3RJUmFaQjlqZ0ZTazZZcjlM
            YlhhMlZ5Q1RPSG9keEM3b3dTdS9Gd00KLS0tIEgzWUNTSm5UZVpXSHYwdUFaakNZ
            VmlOOXcvd25rUVRHdnEwMHg4Q05Ubk0KKHwhEOnwaLgpceLbVoCppIqHZxdvx5Md
            uS0ogOjfIe96l2XKJFYCOcBgBnKtUup4w5GgfHh7GF/3fZMye/OR7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-04T15:32:23Z"
    mac: ENC[AES256_GCM,data:FrGu3lUaSqxR8ycmTUcyv1eePduTIoYsTrCXOjhy+PnFmeFgU6143MOZdOXMF4blsjaePDO6vAqBzdf6rEXlxXEzdtr/lsE4SUf1ykFjb4WBUUG9K5l+rr2gW+pkCgSIgxwxSuOQkDhPohW/nGlkGxU2P18Qt462OjhoCYq9fY4=,iv:NaxqJwNX81KvmM44NWGzpoaKOfOexbOcyzFscjZt6WM=,tag:5OSLw6WC+zvOSjtE+mEvOQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
