apiVersion: v1
kind: ConfigMap
metadata:
  name: linkding-configmap
  namespace: linkding
data:
  LD_DB_HOST: "linkding-db-staging-rw" # sollte dem Service-Namen entsprechen
  LD_DB_PORT: "5432"
  # Eventuell weitere nicht-sensible Einstellungen, z.B. LD_DB_ENGINE, SITE_BASE_URL etc.
