apiVersion: v1
kind: ConfigMap
metadata:
  name: linkding-configmap
  namespace: linkding
data:
  LD_DB_ENGINE: "postgres"
  LD_DB_DATABASE: "linkding" # Name der Datenbank
  LD_DB_HOST: "linkding-db-staging-rw" # MUSS exakt mit dem Secret übereinstimmen
  LD_DB_PORT: "5432"
