apiVersion: v1
kind: Secret
metadata:
  name: linkding-superuser
  namespace: linkding
type: Opaque
stringData:
  LD_DB_USER: "linkding"
  LD_DB_PASSWORD: "eBUKCALsDBu7SmmiWEGMr3t96jsISel8QNUTRH9pBtCa1FNhyCu3GLYbBTV2aO8p"
