apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: linkding-db-staging
  namespace: linkding
spec:
  description: Postgres database cluster for linkding
  imageName: ghcr.io/cloudnative-pg/postgresql:16.6-30-bookworm
  instances: 2

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - p3

  # ...restlicher Code...

  inheritedMetadata:
    labels:
      app: linkding-database

  bootstrap:
    initdb:
      database: linkding
      owner: linkding

  monitoring:
    enablePodMonitor: true
    customQueriesConfigMap:
      - name: postgres-custom-metrics
        key: queries.yaml

  storage:
    size: 2Gi
    pvcTemplate:
      accessModes:
        - ReadWriteOnce

  backup:
    barmanObjectStore:
      destinationPath: "s3://piclusterhomelab/linkding-new/"
      s3Credentials:
        accessKeyId:
          name: aws-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: aws-creds
          key: ACCESS_SECRET_KEY
    retentionPolicy: 7d