apiVersion: v1
kind: Secret
metadata:
  name: linkding-superuser
  namespace: linkding
type: Opaque
stringData:
  LD_DB_USER: "linkding"
  LD_DB_PASSWORD: "iHcRKygrg1NCF1Ap5KCeAUjQ77gx2NYSmmWV8UcBVjjyIzAKC0EftDUzwy56DqKB"
