apiVersion: v1
kind: Secret
metadata:
    name: linkding-superuser
    namespace: linkding
type: Opaque
stringData:
    LD_DB_USER: ENC[AES256_GCM,data:1eirS6qjllE=,iv:5zsJltWfdp5oV0+6YwOTrjnIzx4Cf50cDj7SzY4U47A=,tag:zEroMfSlGOPpK370fZS8Xw==,type:str]
    LD_DB_PASSWORD: ENC[AES256_GCM,data:p6qaEx9UxBpK3X2i3/2JjCb1g9zOikkS5EdaL0dp9+fO41E7Kbbmuw05nk2rdwLd9pI8XXVlKl0G36yz60Xckg==,iv:UYmc4hbJ0S8vOM2mFb/m99bnDKYO13ssV02NMPBMSvM=,tag:lmBEFRpz0JOeX5laUt44pw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10ysfmeczf9rvgd6alaqe4ffna3wm7s78y9wkysargvd7fxaq5u4s8gru2g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvUVFJWDBXdHJ4RG5DNDgx
            QVRqamlVRlRUYmZhSy9LQXVwa25EWHFXSldvCk5LWjdmaXFmb2E4clVkeG1waE5U
            UUtWM2NBcmdqajFBaGNsd0RZY0EwNVkKLS0tIG5KQ0lNcGhTd0wwa252ZWc0ZmZF
            czRlMmVyWWU5bHd4dnVTaGxkb1JoUEEKCNp+aRtDVjde3EwBrlhEdzh3ntEkJ/zv
            0ySSreLGMFGSknUzqGoyvCBOoGzumhJKcxuwiVSPmcjBPCaEJ7AnkQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-05T21:39:57Z"
    mac: ENC[AES256_GCM,data:DsEaGt92YIBBCH89veW8Gj3DzJeOER4gLsJwZXhTKWDgnawzSnsLxT8NT+wv68bmdVIow5VNLh5iuquOdKgMFsjuDM2oRQHPy7Q8dUbEDa5EDg+HHDJ5KrfR6d6v/Wdjz1jqc4OkY2FZgs0NRYGG3xLt5Q7UZi3W5lC+n+doB6o=,iv:ySLwQiMHgEciyzQoX9EM2fW/NF6+CmwcTB6RZrx3jJg=,tag:fmjMh28RNu2XntmmggMSDw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
