apiVersion: v1
kind: Secret
metadata:
  name: linkding-superuser
  namespace: linkding
type: Opaque
stringData:
  LD_DB_USER: ENC[AES256_GCM,data:mhdK0AwVvrc=,iv:KsKHm/RKbEoKMNDszUCDH9YE9ca9Lfx3LBkHlBfftUg=,tag:hE4wvkziDTqDHggjUrP9Wg==,type:str]
  LD_DB_PASSWORD: ENC[AES256_GCM,data:piOOSFK3591w6OmbaQ7rheLxYzH8fL7T+cjg4i2GD2l0LNztegpOeCvGicuNZmzlXnScIXaby5LY15qisziJmg==,iv:B3IP5foTny5vK3QuMduGQFTc56DBQ6SPB2Q9jP295lc=,tag:4h6iCIh1UZKbbVUotc9J8A==,type:str]
  LD_DB_HOST: ENC[AES256_GCM,data:La2cJi/xCs9Zq2AFiLIh64dwbm1AjA6nF5PIc/YTyg==,iv:6gOxG474eNcKxMepVG9JoMM2jaM1m/KZU1OCEPT7iwc=,tag:395cibSDhxwVk3dGtL0LEw==,type:str]
  LD_DB_PORT: ENC[AES256_GCM,data:5es9SA==,iv:t/KtgmW5fU2Lfs03lSsdRES/O13EJFHmNQJDsLEkpnw=,tag:RDF6N/RtJx2PK/g86Xv67g==,type:str]
  LD_DB_NAME: ENC[AES256_GCM,data:Gw2miuu6Vj4=,iv:cvFu/diYJ2MhF/qWpMCGfAs+C0OgHsItK8YMj0lAubk=,tag:FAH5iJhCvw1oiKSUwMoC5Q==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age10ysfmeczf9rvgd6alaqe4ffna3wm7s78y9wkysargvd7fxaq5u4s8gru2g
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvMm82QXZ0RHlPeCtWWDVs
        VzNjYnJNcXQ5VkgrbysvTTZIaDFSdGloeWk4Cmo0ek0vWkdsRExFaHphSDRPa3g3
        VzFLRUROYkRwQjRnb3g0VStlOGxaeWsKLS0tIGFwd1FxdnAwWXpidFZxUG4yMUNW
        dE9ETWFkYU1JVk9vUkRxRXljSnduMGMKCjVktJXBJgG5h42g2cdGTDMtr5Q7qz3o
        U0elaQQCM4GHEhboVotcl6YNkYeOIV0qGICiAT0W1XR2B17JLbChFw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-22T03:37:38Z"
  mac: ENC[AES256_GCM,data:MQA0wYSQWjGOhp6roULyTe6fDg9QJb+vKFdjYos/us7MgexE/QvNRLZyE+mclq9LKtaukFQfqLWXKCosJk5z7Q9wlVtgPqhrTF/z6Er2WcyR4/7fjOT1zQ5VrWZT+ktzoHXJqjoIllrMrYOsWuGyKudNL1K5RjBw/YZOaI1wvN4=,iv:yjsiz11+qbtP+gJPn1ou4b0Hze41gAIA0TCIgPBHGmk=,tag:cV2c4haOjgpaNcRaETLnHQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.4
###ee
