apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: linkding-db-staging
  namespace: linkding
spec:
  description: Postgres database cluster for linkding
  imageName: ghcr.io/cloudnative-pg/postgresql:16.6-30-bookworm
  instances: 1 # + 1 replica

  inheritedMetadata:
    labels:
      app: linkding-database

  bootstrap:
    initdb:
      database: linkding
      owner: linkding

  monitoring:
    enablePodMonitor: true

  storage:
    size: 1Gi
    pvcTemplate:
      accessModes:
        - ReadWriteOnce

  backup:
    barmanObjectStore:
      destinationPath: "s3://piclusterhomelab/linkding/"
      s3Credentials:
        accessKeyId:
          name: aws-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: aws-creds
          key: ACCESS_SECRET_KEY
    retentionPolicy: 7d
