apiVersion: v1
kind: Secret
metadata:
  name: linkding-superuser
  namespace: linkding
type: Opaque
stringData:
  LD_SUPERUSER_NAME: "app"
  LD_SUPERUSER_PASSWORD: "Nrz2rQyg2v29WEOMlP74sJkfim4O18WwWXyFfCLvoOxeFXPJim8pTAJDfPKlYztz"
