apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: linkding
resources:
  - ../../base/linkding/
  - cloudflare.yaml
  - cloudflare-secret.yaml
  - linkding-container-env-secret.yaml
  - ingress.yaml
  - configmap.yaml
  - database.yaml # Temporarily disabled
  # - linkding-container-env.yaml  #temporäry disabled
  - aws-credentials.yaml
  - scheduled-backup.yaml
  # - networkpolicy.yaml
  - database-secret.yaml # Temporarily disabled

# Strategic Merge: Staging database-secret überschreibt Base linkding-secret
#patchesStrategicMerge:
#  - database-secret.yaml # Überschreibt ../../base/linkding/linkding-secret.yaml