apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: linkding
resources:
  - ../../base/linkding/
  - cloudflare.yaml
  - cloudflare-secret.yaml
  - linkding-container-env-secret.yaml
  - ingress.yaml
  - configmap.yaml
  # - database.yaml # Temporarily disabled
  # - database-secret.yaml # Temporarily disabled
  - aws-credentials.yaml
  - scheduled-backup.yaml
  # - networkpolicy.yaml
#  - postgres-custom-metrics.yaml
