# Linkding namespace - default allow internal communication
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: linkding-internal-comms
  namespace: linkding
spec:
  description: "Allow all pods within linkding namespace to communicate"
  endpointSelector: {}
  ingress:
    # Allow all pods in the same namespace to communicate freely
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: linkding
    # Allow traffic from monitoring namespace
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: monitoring
    # Allow traffic from pgAdmin
    - fromEndpoints:
        - matchLabels:
            app: pgadmin
            io.kubernetes.pod.namespace: pgadmin
    # Allow traffic from traefik ingress
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            name: traefik
    # Allow CloudNativePG operator access to database
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: cnpg-system
  egress:
    # Allow DNS access for all pods
    - toEndpoints:
        - matchLabels:
            k8s-app: kube-dns
            io.kubernetes.pod.namespace: kube-system
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
          rules:
            dns:
              - matchPattern: "*"
        - ports:
            - port: "53"
              protocol: TCP
    # Allow access to k8s API for CloudNativePG
    - toEntities:
        - kube-apiserver
      toPorts:
        - ports:
            - port: "6443"
              protocol: TCP
    # Allow limited outbound internet access (HTTPS only)
    - toEntities:
        - world
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
---
# pgAdmin basic policy
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: pgadmin-basic
  namespace: pgadmin
spec:
  description: "Basic permissions for pgAdmin"
  endpointSelector:
    matchLabels:
      app: pgadmin
  ingress:
    # Allow traefik to access pgAdmin
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
  egress:
    # Allow DNS
    - toEndpoints:
        - matchLabels:
            k8s-app: kube-dns
            io.kubernetes.pod.namespace: kube-system
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
          rules:
            dns:
              - matchPattern: "*"
        - ports:
            - port: "53"
              protocol: TCP
    # Allow access to linkding namespace
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: linkding
