# 1. DENY-ALL: Alles wird standardmäßig blockiert
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: deny-all
  namespace: linkding
spec:
  endpointSelector: {}
  ingress: []
  egress: []
### kommentiert nachdem ich es hinbekommen hab wuhu :)
---

# 2. App-Policy: Erlaube Traffic zur App (z.B. von cloudflared, monitoring, operator)
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: linkding-app
  namespace: linkding
spec:
  endpointSelector:
    matchLabels:
      policy-type: "app"
  ingress:
    # Erlaube Traffic von cloudflared im selben Namespace
    - fromEndpoints:
        - matchLabels:
            app: cloudflared
            io.kubernetes.pod.namespace: linkding
    # Erlaube Traffic von Monitoring
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: monitoring
    # Erlaube Traffic vom Postgres-Operator (Namespace ggf. anpassen)
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: cnpg-system
    # Optional: Erlaube Traffic von überall (z.B. für Debugging)
    # - fromEndpoints:
    #     - {}
  egress:
    # DNS
    - toEndpoints:
        - matchLabels:
            k8s-app: kube-dns
            io.kubernetes.pod.namespace: kube-system
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
          rules:
            dns:
              - matchPattern: "*"
    # Erlaube alles im Namespace (optional)
    - toEndpoints:
        - {}
    # Internet
    - toEntities:
        - world
      toPorts:
        - ports:
            - port: "443"
            - port: "80"
            - port: "7844"

---

# 3. Database-Policy: Erlaube Traffic zur Datenbank (z.B. von App, Monitoring, Operator)
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: linkding-database
  namespace: linkding
spec:
  endpointSelector:
    matchLabels:
      policy-type: "database"
  ingress:
    # Erlaube Traffic von App
    - fromEndpoints:
        - matchLabels:
            policy-type: "app"
            io.kubernetes.pod.namespace: linkding
    # Erlaube Traffic von Monitoring
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: monitoring
    # Erlaube Traffic vom Postgres-Operator (Namespace ggf. anpassen)
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: cnpg-system
  egress:
    # DNS
    - toEndpoints:
        - matchLabels:
            k8s-app: kube-dns
            io.kubernetes.pod.namespace: kube-system
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
          rules:
            dns:
              - matchPattern: "*"
    # Erlaube alles im Namespace (optional)
    - toEndpoints:
        - {}
    # Kubernetes API Server
    - toEntities:
        - kube-apiserver
      toPorts:
        - ports:
            - port: "6443"
    # Internet
    - toEntities:
        - world
      toPorts:
        - ports:
            - port: "443"