# Default deny policy
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: deny-all
  namespace: linkding
spec:
  endpointSelector: {}
  ingress:
    - {}
  egress:
    - {}
---
# Linkding application policy
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: linkding-app-policy
  namespace: linkding
spec:
  endpointSelector:
    matchLabels:
      app: linkding
  ingress:
    - fromEndpoints:
        - {} # Allow all inbound connections
  egress:
    - toEndpoints:
        - {} # Allow connections to all pods
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
              # DNS pattern matching
          rules:
            dns:
              - matchPattern: "*"
        - ports:
            - port: "53"
              protocol: TCP
    - toEntities:
        - world
      toPorts:
        - ports:
            - port: "443"
        - ports:
            - port: "80"
        - ports:
            - port: "7844"
---
# Database policy
# Database policy
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: database-policy
  namespace: linkding
spec:
  endpointSelector:
    matchExpressions:
      - key: cnpg.io/cluster
        operator: Exists
  ingress:
    - fromEndpoints:
        - {} # Allow all inbound connections
  egress:
    - toEndpoints:
        - {} # Allow connections to all pods
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
          rules:
            dns:
              - matchPattern: "*"
        - ports:
            - port: "53"
              protocol: TCP
    # Fix for K8s API server access
    - toEntities:
        - host
        - remote-node
        - kube-apiserver
    - toEntities:
        - world
      toPorts:
        - ports:
            - port: "443"
---
# Cloudflared policy
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: cloudflared-policy
  namespace: linkding
spec:
  endpointSelector:
    matchLabels:
      app: cloudflared
  ingress:
    - fromEndpoints:
        - {} # Allow all inbound connections
  egress:
    - toEndpoints:
        - {} # Allow connections to all pods
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
          rules:
            dns:
              - matchPattern: "*"
        - ports:
            - port: "53"
              protocol: TCP
    - toEntities:
        - world
      toPorts:
        - ports:
            - port: "443"
        - ports:
            - port: "7844"
---
# pgAdmin policy (separate namespace)
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: pgadmin-policy
  namespace: pgadmin
spec:
  endpointSelector:
    matchLabels:
      app: pgadmin
  ingress:
    - fromEndpoints:
        - {} # Allow all inbound connections
  egress:
    - toEndpoints:
        - {} # Allow connections to all pods in cluster
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
          rules:
            dns:
              - matchPattern: "*"
