apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-custom-metrics
  namespace: linkding
data:
  queries.yaml: |
    pg_database:
      query: "SELECT pg_database.datname, pg_database_size(pg_database.datname) as size_bytes FROM pg_database"
      metrics:
        - datname:
            usage: "LABEL"
            description: "Name of the database"
        - size_bytes:
            usage: "GAUGE"
            description: "Size of the database in bytes"

    pg_stat_activity:
      query: "SELECT state, count(*) as count FROM pg_stat_activity GROUP BY state"
      metrics:
        - state:
            usage: "LABEL"
            description: "Connection state"
        - count:
            usage: "GAUGE"
            description: "Connection count"

    pg_locks:
      query: "SELECT mode, count(*) as count FROM pg_locks GROUP BY mode"
      metrics:
        - mode:
            usage: "LABEL"
            description: "Lock mode"
        - count:
            usage: "GAUGE"
            description: "Number of locks"
