# scheduled-backup.yaml
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: linkding-db-staging-backup
  namespace: linkding
spec:
  schedule: "0 8 * * *" # Jeden Tag um 8:00 Uhr Berlin Zeit
  backupOwnerReference: cluster
  cluster:
    name: linkding-db-staging
