# File path: /Users/timour/Desktop/kubecraft/mealie/homelabtm/pi-cluster/clusters/staging/infrastructure-core.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-core
  namespace: flux-system
spec:
  interval: 30m
  path: "./homelabtm/pi-cluster/infrastructure/controllers/core"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  timeout: 5m
  dependsOn:
    - name: infrastructure-controllers  # Add this dependency