# /infrastructure/controllers/base/velero/aws-credentials.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: velero-container-env
  namespace: velero
  annotations:
    force-sync: "true"
    reconcile.external-secrets.io/verbose-logging: "true"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: velero-aws-credentials
    creationPolicy: Owner
    template:
      data:
        cloud: |
          [default]
          aws_access_key_id = {{ .ACCESS_KEY_ID }}
          aws_secret_access_key = {{ .SECRET_ACCESS_KEY }}
          region = eu-central-1
  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: picluster/backup-credentials
        property: ACCESS_KEY_ID
    - secretKey: SECRET_ACCESS_KEY
      remoteRef:
        key: picluster/backup-credentials
        property: SECRET_ACCESS_KEY
