# /infrastructure/controllers/base/velero/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
  - volume-snapshot-class.yaml
  - aws-credentials.yaml
  - daily-backup-schedule.yaml
