# /infrastructure/controllers/base/velero/release.yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 15m
  chart:
    spec:
      chart: velero
      version: "5.0.2"
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: velero
  values:
    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.12.0
        volumeMounts:
          - mountPath: /target
            name: plugins

    nodeSelector:
      kubernetes.io/hostname: p3

    configuration:
      provider: aws
      backupStorageLocation:
        name: aws
        provider: aws
        default: true
        bucket: piclusterhomelab
        config:
          region: eu-central-1
          s3ForcePathStyle: true
      features: EnableCSI

    credentials:
      existingSecret: velero-aws-credentials

    snapshotsEnabled: false

    resources:
      requests:
        cpu: "100m"
        memory: "200Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
