# /infrastructure/controllers/base/velero/repository.yaml
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: vmware-tanzu
  namespace: velero
spec:
  interval: 1h
  url: https://vmware-tanzu.github.io/helm-charts
