# HTTPs Redirect Middleware
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: homepage-redirect-https
  namespace: homepage
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
  annotations:
    gethomepage.dev/description: "Homelab Dashboard"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: "Cluster Management"
    gethomepage.dev/icon: "homepage.png"
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    # Verwende die Middleware für die Umleitung
    traefik.ingress.kubernetes.io/router.middlewares: homepage-redirect-https@kubernetescrd
    external-dns.alpha.kubernetes.io/hostname: homepage.timourhomelab.org
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - homepage.timourhomelab.org
      secretName: homepage-tls
  rules:
    - host: homepage.timourhomelab.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: homepage
                port:
                  number: 3000