# homepage-route.yaml
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-to-https
  namespace: homepage
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homepage-https
  namespace: homepage
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`homepage.timourhomelab.org`)
      kind: Rule
      services:
        - name: homepage
          port: 3000
  tls:
    secretName: homepage-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homepage-http
  namespace: homepage
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`homepage.timourhomelab.org`)
      kind: Rule
      middlewares:
        - name: redirect-to-https
      services:
        - name: homepage
          port: 3000