apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homepage
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - clusterrole.yaml # This probably contains both ClusterRole and ClusterRoleBinding
  # - clusterrolebinding.yaml  # Remove this line, file doesn't exist
  - configmap.yaml
  - secret.yaml
  - service.yaml
  - deployment.yaml
  - ingress.yaml # Uncomment if needed
