# homelabtm/pi-cluster/monitoring/configs/staging/grafana/datasources.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
  labels:
    grafana_datasource: "1"
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      uid: prometheus
      url: http://kube-prometheus-stack-prometheus.monitoring:9090/
      isDefault: true
    - name: Loki
      type: loki
      uid: loki
      url: http://loki-headless.monitoring:3100/
      access: proxy
      jsonData:
        derivedFields:
          # ✅ B3-Traces aus Emojivoto-Logs
          - datasourceUid: tempo
            matcherRegex: '"X-B3-Traceid":"([0-9a-fA-F]+)"'
            name: TraceID
            url: $${__value.raw}
          # ✅ B3-Traces aus Traefik-Access-Logs
          - datasourceUid: tempo
            matcherRegex: 'X-B3-Traceid=([0-9a-fA-F]+)'
            name: TraceID
            url: $${__value.raw}
          # ✅ Generic TraceID-Pattern
          - datasourceUid: tempo
            matcherRegex: 'trace_id["\s]*[:=]["\s]*([0-9a-fA-F]+)'
            name: TraceID
            url: $${__value.raw}
    - name: Tempo
      uid: tempo
      type: tempo
      access: proxy
      url: http://tempo-query-frontend-discovery.tempo.svc.cluster.local:3100
      jsonData:
        httpMethod: GET
        serviceMap:
          datasourceUid: prometheus
        search:
          hide: false
        nodeGraph:
          enabled: true
        lokiSearch:
          datasourceUid: loki
        tracesToMetrics:
          datasourceUid: prometheus
        tracesToLogs:
          datasourceUid: loki
          # ✅ Trace-to-Logs-Korrelation
          filterByTraceID: true
          filterBySpanID: true
          tags:
            - key: service.name
              value: service_name





#apiVersion: v1
#kind: ConfigMap
#metadata:
  #name: grafana-datasources
  #namespace: monitoring
  #labels:
  #  grafana_datasource: "1"
#data:
  #datasource.yaml: |-
   # apiVersion: 1
   # datasources:
   # - name: Prometheus
   #   type: prometheus
    #  uid: prometheus
   #   url: http://kube-prometheus-stack-prometheus.monitoring:9090/
   #   isDefault: true
   #   jsonData:
   #     httpMethod: POST
   #     timeInterval: 30s
   # - name: Alertmanager
    #  type: alertmanager
  #    uid: alertmanager
    #  url: http://prometheus-stack-kube-prom-alertmanager.monitoring:9093/
   #   access: proxy
    #  jsonData:
    #    handleGrafanaManagedAlerts: false
    #    implementation: prometheus
   # - name: Loki
   #   type: loki
   #   uid: loki
   #   url: http://loki.monitoring:3100/
  #  - name: Tempo
  #    type: tempo
   #   uid: tempo
   #   url: http://tempo-query-frontend-discovery.tempo.svc.cluster.local:3100  # ✅ Tutorial-URL
   #   access: proxy
   #   jsonData:
   ##     httpMethod: GET
     #   serviceMap:
     #     datasourceUid: prometheus
     #   search:
     #     hide: false
     #   nodeGraph:
     #     enabled: true
     #   lokiSearch:
      #    datasourceUid: loki

