apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kibana
  namespace: logging
spec:
  interval: 15m
  chart:
    spec:
      chart: kibana
      version: "7.17.3"
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: logging
  values:
    elasticsearchHosts: "http://elasticsearch-master:9200"

    # Resources optimized for Raspberry Pi
    resources:
      requests:
        cpu: "200m"
        memory: "400Mi"
      limits:
        cpu: "500m"
        memory: "600Mi"

    # Run on worker node to distribute load
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - p2

    # Ingress configuration
    ingress:
      enabled: true
      ingressClassName: traefik
      hosts:
        - host: kibana.timourhomelab.org
          paths:
            - path: /
              pathType: Prefix
