apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kibana
  namespace: logging
spec:
  interval: 15m
  chart:
    spec:
      chart: kibana
      version: "7.17.3"
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: logging
  values:
    # Enhanced resources for P3
    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "1000m"
        memory: "2Gi"

    # Connect to Elasticsearch
    elasticsearchHosts: "http://elasticsearch-master:9200"

    # Add ingress
    ingress:
      enabled: true
      ingressClassName: traefik
      hosts:
        - host: kibana.timourhomelab.org
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: kibana-tls
          hosts:
            - kibana.timourhomelab.org
