apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kibana
  namespace: logging
spec:
  interval: 15m
  chart:
    spec:
      chart: kibana
      version: "7.17.3"
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: logging
  install:
    remediation:
      retries: 3
  values:
    elasticsearchHosts: "http://elasticsearch-master:9200"

    extraEnvs:
      - name: "ELASTICSEARCH_USERNAME"
        valueFrom:
          secretKeyRef:
            name: elasticsearch-credentials
            key: username
      - name: "ELASTICSEARCH_PASSWORD"
        valueFrom:
          secretKeyRef:
            name: elasticsearch-credentials
            key: password

    # Disable built-in ingress, we'll use our own
    ingress:
      enabled: false

    # Keep it as ClusterIP like Grafana
    service:
      type: ClusterIP
      port: 5601
