apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kibana
  namespace: logging
spec:
  interval: 15m
  chart:
    spec:
      chart: kibana
      version: "7.17.3"
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: logging
  values:
    elasticsearchHosts: "http://elasticsearch-master:9200"

    # Authentication
    kibanaConfig:
      kibana.yml: |
        elasticsearch.username: elastic
        elasticsearch.password: ${ELASTICSEARCH_PASSWORD}

    extraEnvs:
      - name: ELASTICSEARCH_PASSWORD
        valueFrom:
          secretKeyRef:
            name: elasticsearch-credentials
            key: password

    # Resources for Raspberry Pi
    resources:
      requests:
        cpu: 200m
        memory: 500Mi
      limits:
        cpu: 500m
        memory: 1Gi

    # Run on a specific node
    nodeSelector:
      kubernetes.io/hostname: master
