apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kibana
  namespace: logging
spec:
  interval: 15m
  chart:
    spec:
      chart: kibana
      version: "7.17.3"
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: logging
  values:
    # Keep Kibana near Elasticsearch
    nodeSelector:
      kubernetes.io/hostname: p3

    # Lightweight resources
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "300m"
        memory: "512Mi"

    # Connect to single-node ES
    elasticsearchHosts: "http://elasticsearch-master:9200"

    # Add some security settings
    extraEnvs:
      - name: XPACK_SECURITY_ENABLED
        value: "false"
      - name: ELASTICSEARCH_USERNAME
        value: ""
      - name: ELASTICSEARCH_PASSWORD
        value: ""

    # Your ingress configuration
    ingress:
      enabled: true
      ingressClassName: traefik
      hosts:
        - host: kibana.timourhomelab.org
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: kibana-tls
          hosts:
            - kibana.timourhomelab.org
