# File: homelabtm/pi-cluster/infrastructure/controllers/base/efk/elasticsearch/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - release.yaml
  - services.yaml
