apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: elasticsearch
  namespace: logging
spec:
  interval: 15m
  chart:
    spec:
      chart: elasticsearch
      version: "7.17.3"
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: logging
  values:
    # Three-node cluster for redundancy
    replicas: 3
    minimumMasterNodes: 2

    # Increased memory settings for 16GB system
    esJavaOpts: "-Xmx4g -Xms4g"

    # Resource limits for P3 hardware
    resources:
      requests:
        cpu: "1000m"
        memory: "5Gi"
      limits:
        cpu: "2000m"
        memory: "6Gi"

    # Use local-path storage with larger allocation
    volumeClaimTemplate:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "local-path"
      resources:
        requests:
          storage: 40Gi

    # Add init container to set vm.max_map_count
    extraInitContainers:
      - name: sysctl
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
