apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: elasticsearch
  namespace: logging
spec:
  interval: 15m
  chart:
    spec:
      chart: elasticsearch
      version: "7.17.3"
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: logging
  values:
    # Single node for Pi
    replicas: 1
    minimumMasterNodes: 1

    # Critical: Fix memory settings
    esJavaOpts: "-Xms256m -Xmx256m"

    # Remove node selector to let it schedule anywhere
    nodeSelector: {}

    # Low resource settings for Pi hardware
    resources:
      requests:
        cpu: "100m"
        memory: "512Mi"
      limits:
        cpu: "500m"
        memory: "1Gi"

    # Storage needs
    volumeClaimTemplate:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "local-path"
      resources:
        requests:
          storage: 5Gi

    # Configuration for single node
    extraEnvs:
      - name: discovery.type
        value: single-node
      - name: cluster.initial_master_nodes
        value: ""

    # VM settings
    sysctlInitContainer:
      enabled: true
