apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: elasticsearch
  namespace: logging
spec:
  interval: 15m
  chart:
    spec:
      chart: elasticsearch
      version: "7.17.3"
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: logging
  values:
    # Two nodes for redundancy
    replicas: 2
    minimumMasterNodes: 1

    # Cluster name
    clusterName: "elasticsearch"

    # Resource allocation - use less memory for Pi
    esJavaOpts: "-Xms512m -Xmx512m"

    # Resource limits suitable for Pi
    resources:
      requests:
        cpu: "200m"
        memory: "768Mi"
      limits:
        cpu: "500m"
        memory: "1Gi"

    # Storage configuration
    volumeClaimTemplate:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "local-path"
      resources:
        requests:
          storage: 5Gi

    # Required for Elasticsearch
    sysctlInitContainer:
      enabled: true

    # Use soft anti-affinity to allow nodes to run on same hardware if needed
    antiAffinity: "soft"

    # Important settings for a small cluster
    esConfig:
      elasticsearch.yml: |
        # Default shard allocation to ensure replica creation
        index.number_of_shards: 1
        index.number_of_replicas: 1

        # Performance optimizations for small clusters
        indices.memory.index_buffer_size: 10%
        indices.queries.cache.size: 5%

        # Disable monitoring to save resources
        xpack.monitoring.enabled: false

        # Lower circuit breaker to prevent OOM
        indices.breaker.total.limit: 70%
