apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: elasticsearch
  namespace: logging
spec:
  interval: 15m
  chart:
    spec:
      chart: elasticsearch
      version: "7.17.3"
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: logging
  values:
    # Node affinity to run on your powerful node
    nodeSelector:
      kubernetes.io/hostname: p3 # Replace with your actual node name

    # Run a 3-node cluster all on the same powerful node
    replicas: 3
    minimumMasterNodes: 2

    # Higher memory settings for 16GB RAM system
    esJavaOpts: "-Xms4g -Xmx4g"

    # Resources appropriate for 16GB system
    resources:
      requests:
        cpu: "1000m"
        memory: "5Gi"
      limits:
        cpu: "2000m"
        memory: "6Gi"

    # Local storage on SSD
    volumeClaimTemplate:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "local-path"
      resources:
        requests:
          storage: 25Gi

    # Performance optimizations
    esConfig:
      elasticsearch.yml: |
        indices.memory.index_buffer_size: 30%
        indices.queries.cache.size: 15%
        bootstrap.memory_lock: true

    sysctlInitContainer:
      enabled: true
