apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: elasticsearch
  namespace: logging
spec:
  interval: 15m
  chart:
    spec:
      chart: elasticsearch
      version: "7.17.3"
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: logging
  values:
    # Target 16GB RAM node
    nodeSelector:
      kubernetes.io/hostname: p3

    # Single node for Pi cluster
    replicas: 1
    minimumMasterNodes: 1

    # Critical ARM-specific JVM options
    esJavaOpts: "-Des.cgroups.hierarchy.override=/ -Xms512m -Xmx512m"

    # Additional environment variables for ARM compatibility
    extraEnvs:
      - name: node.store.allow_mmap
        value: "false"
      - name: bootstrap.memory_lock
        value: "false"
      - name: ES_JAVA_HOME
        value: /usr/share/elasticsearch/jdk
      - name: JAVA_HOME
        value: /usr/share/elasticsearch/jdk
      - name: DISABLE_JVM_HEAP_DUMP_ON_OOM
        value: "true"
      - name: READINESS_PROBE_TIMEOUT
        value: "10"

    # Optimized configuration for ARM
    esConfig:
      elasticsearch.yml: |
        discovery.type: single-node
        bootstrap.memory_lock: false
        xpack.security.enabled: false
        xpack.monitoring.enabled: false
        indices.fielddata.cache.size: 10%
        indices.queries.cache.size: 5%
        indices.memory.index_buffer_size: 10%
        thread_pool.search.size: 5
        thread_pool.write.size: 4

    # Reasonable resource requests for Pi
    resources:
      requests:
        cpu: "200m"
        memory: "768Mi"
      limits:
        cpu: "1"
        memory: "1Gi"

    # Storage configuration
    volumeClaimTemplate:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "local-path"
      resources:
        requests:
          storage: 10Gi

    # Init container for sysctls
    sysctlInitContainer:
      enabled: true

    # Security context
    securityContext:
      runAsUser: 1000
      fsGroup: 1000
      runAsNonRoot: true

    # Probe settings
    readinessProbe:
      initialDelaySeconds: 90
      periodSeconds: 10
      timeoutSeconds: 5
      successThreshold: 3
      failureThreshold: 10

    # Required for ARM systems
    antiAffinity: "soft"
