apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: elasticsearch
  namespace: logging
spec:
  interval: 15m
  chart:
    spec:
      chart: elasticsearch
      version: "7.17.3"
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: logging
  values:
    # Single node for Pi cluster - much lighter footprint
    replicas: 1
    minimumMasterNodes: 1

    # Remove node selector to allow scheduling anywhere
    # nodeSelector:
    #   kubernetes.io/hostname: p3

    # Very conservative memory settings for Pi
    esJavaOpts: "-Xms256m -Xmx256m"

    # Drastically reduced resource requirements
    resources:
      requests:
        cpu: "100m"
        memory: "512Mi"
      limits:
        cpu: "500m"
        memory: "1Gi"

    # Local storage configuration - smaller size
    volumeClaimTemplate:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "local-path"
      resources:
        requests:
          storage: 10Gi

    # Add init container for system settings
    sysctlInitContainer:
      enabled: true
