apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: elasticsearch
  namespace: logging
spec:
  interval: 15m
  chart:
    spec:
      chart: elasticsearch
      version: "7.17.3"
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: logging
  values:
    clusterName: "elasticsearch"
    nodeGroup: "master"

    # Two master nodes for high availability
    replicas: 2
    minimumMasterNodes: 1

    # Force distribution of pods across nodes
    antiAffinity: "hard"
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: elasticsearch-master

    # Node affinity to specify which nodes can run ES pods
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - master
                  - p2

    # Resources optimized for Raspberry Pi
    # Update in elasticsearch/release.yaml
    resources:
      requests:
        cpu: "250m"
        memory: "512Mi"
      limits:
        cpu: "500m"
        memory: "1Gi"

    # Reduce JVM heap size
    esJavaOpts: "-Xmx256m -Xms256m"

    # Storage configuration
    volumeClaimTemplate:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "local-path"
      resources:
        requests:
          storage: 10Gi

    # Security settings
    esConfig:
      elasticsearch.yml: |
        xpack.security.enabled: true
        xpack.security.authc:
          api_key.enabled: true
          anonymous:
            username: elastic
            roles: superuser
            authz_exception: false

    # Add credentials from Secret
    extraEnvs:
      - name: ELASTIC_PASSWORD
        valueFrom:
          secretKeyRef:
            name: elasticsearch-credentials
            key: ELASTIC_PASSWORD
