apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: elasticsearch
  namespace: logging
spec:
  interval: 15m
  chart:
    spec:
      chart: elasticsearch
      version: "7.17.3"
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: logging
  values:
    # Single node configuration optimized for Pi
    replicas: 1
    minimumMasterNodes: 1

    # Force placement on the 16GB node
    nodeSelector:
      kubernetes.io/hostname: p3 # Replace with your 16GB node name

    # Critical: Set small Java heap for Pi
    esJavaOpts: "-Xms512m -Xmx512m"

    # Optimized resource limits
    resources:
      requests:
        cpu: "100m"
        memory: "768Mi"
      limits:
        cpu: "500m"
        memory: "1Gi"

    # Storage configuration
    volumeClaimTemplate:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "local-path"
      resources:
        requests:
          storage: 20Gi

    # Essential settings for single-node mode
    extraEnvs:
      - name: discovery.type
        value: single-node
      - name: cluster.initial_master_nodes
        value: ""

    # Required for Elasticsearch
    sysctlInitContainer:
      enabled: true
