apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-lb
  namespace: logging
  labels:
    app: elasticsearch
spec:
  selector:
    app.kubernetes.io/name: elasticsearch-master
  ports:
    - port: 9200
      name: http
      protocol: TCP
  type: ClusterIP
---
# Headless service for direct pod access
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-nodes
  namespace: logging
  labels:
    app: elasticsearch
spec:
  selector:
    app.kubernetes.io/name: elasticsearch-master
  clusterIP: None
  ports:
    - port: 9200
      name: http
      protocol: TCP
