version: '3.8'
services:
  ansible:
    build: .
    container_name: homelab-ansible
    volumes:
      - .:/ansible
      - ~/.ssh:/root/.ssh:ro
    working_dir: /ansible
    command: tail -f /dev/null
    restart: unless-stopped