apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: emojivoto
  namespace: emojivoto
spec:
  ingressClassName: traefik
  rules:
    - host: emojivoto.timourhomelab.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-svc
                port:
                  number: 80