apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tempo
  namespace: tempo
spec:
  interval: 5m
  chart:
    spec:
      chart: tempo-distributed
      version: 1.15.2
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: tempo
  values:
    # ✅ Explizite Ring-Konfiguration über Helm-Chart-Struktur
    
    # Global Config
    global:
      clusterDomain: cluster.local
    
    # ✅ Traces
    traces:
      otlp:
        grpc:
          enabled: true
        http:
          enabled: true
    
    # ✅ Storage
    storage:
      trace:
        backend: s3
        s3:
          bucket: k3s-tempo
          endpoint: minio.minio.svc.cluster.local:9000
          region: eu-west-1
          access_key: ${MINIO_ACCESS_KEY_ID}
          secret_key: ${MINIO_SECRET_ACCESS_KEY}
          insecure: true
          path_style: true
    
    # ✅ Gossip Ring
    gossipRing:
      enabled: true
    
    # ✅ Distributor
    distributor:
      replicas: 1
      extraArgs:
        - '-config.expand-env=true'
      extraEnv:
        - name: MINIO_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: tempo-minio-secret
              key: MINIO_ACCESS_KEY_ID
        - name: MINIO_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: tempo-minio-secret
              key: MINIO_SECRET_ACCESS_KEY
      nodeSelector:
        kubernetes.io/arch: arm64
    
    # ✅ Ingester mit korrekter Ring-Konfiguration
    ingester:
      replicas: 1
      extraArgs:
        - '-config.expand-env=true'
      extraEnv:
        - name: MINIO_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: tempo-minio-secret
              key: MINIO_ACCESS_KEY_ID
        - name: MINIO_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: tempo-minio-secret
              key: MINIO_SECRET_ACCESS_KEY
      nodeSelector:
        kubernetes.io/arch: arm64
      # ✅ Explizite Ring-Konfiguration für Ingester
      config:
        lifecycler:
          ring:
            kvstore:
              store: memberlist
            replication_factor: 1
            heartbeat_period: 5s
            heartbeat_timeout: 1m
            num_tokens: 128
            instance_id: {{ .Env.HOSTNAME }}
    
    # ✅ Compactor
    compactor:
      replicas: 1
      extraArgs:
        - '-config.expand-env=true'
      extraEnv:
        - name: MINIO_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: tempo-minio-secret
              key: MINIO_ACCESS_KEY_ID
        - name: MINIO_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: tempo-minio-secret
              key: MINIO_SECRET_ACCESS_KEY
      nodeSelector:
        kubernetes.io/arch: arm64
    
    # ✅ Querier
    querier:
      replicas: 1
      extraArgs:
        - '-config.expand-env=true'
      extraEnv:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MINIO_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: tempo-minio-secret
              key: MINIO_ACCESS_KEY_ID
        - name: MINIO_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: tempo-minio-secret
              key: MINIO_SECRET_ACCESS_KEY
      nodeSelector:
        kubernetes.io/arch: arm64
    
    # ✅ Query Frontend
    queryFrontend:
      replicas: 1
      extraArgs:
        - '-config.expand-env=true'
      extraEnv:
        - name: MINIO_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: tempo-minio-secret
              key: MINIO_ACCESS_KEY_ID
        - name: MINIO_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: tempo-minio-secret
              key: MINIO_SECRET_ACCESS_KEY
      nodeSelector:
        kubernetes.io/arch: arm64
    
    # ✅ Memcached
    memcached:
      enabled: true
      nodeSelector:
        kubernetes.io/arch: arm64
    
    # ✅ Minio deaktivieren
    minio:
      enabled: false
    
    # ✅ ServiceMonitor
    serviceMonitor:
      enabled: true
      labels:
        release: prometheus