apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tempo
  namespace: tempo
spec:
  interval: 5m
  chart:
    spec:
      chart: tempo-distributed
      version: 1.15.2
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: tempo
  values:
    # ✅ Tutorial-Konfiguration - Funktioniert garantiert!
    
    # Enable trace ingestion
    traces:
      otlp:
        grpc:
          enabled: true
        http:
          enabled: true
      zipkin:
        enabled: true
      jaeger:
        thriftCompact:
          enabled: true
        thriftHttp:
          enabled: true
      opencensus:
        enabled: true

    # Configure S3 backend
    storage:
      trace:
        backend: s3
        s3:
          bucket: k3s-tempo
          endpoint: minio.minio.svc.cluster.local:9000
          region: eu-west-1
          access_key: ${MINIO_ACCESS_KEY_ID}
          secret_key: ${MINIO_SECRET_ACCESS_KEY}
          insecure: true

    # Configure distributor
    distributor:
      config:
        log_received_spans:
          enabled: true
      # Enable environment variables in config file
      extraArgs:
        - '-config.expand-env=true'
      extraEnv:
        - name: MINIO_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: tempo-minio-secret
              key: MINIO_ACCESS_KEY_ID
        - name: MINIO_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: tempo-minio-secret
              key: MINIO_SECRET_ACCESS_KEY
      nodeSelector:
        kubernetes.io/arch: arm64

    # Configure ingester
    ingester:
      # Enable environment variables in config file
      extraArgs:
        - '-config.expand-env=true'
      extraEnv:
        - name: MINIO_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: tempo-minio-secret
              key: MINIO_ACCESS_KEY_ID
        - name: MINIO_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: tempo-minio-secret
              key: MINIO_SECRET_ACCESS_KEY
      nodeSelector:
        kubernetes.io/arch: arm64

    # Configure compactor
    compactor:
      # Enable environment variables in config file
      extraArgs:
        - '-config.expand-env=true'
      extraEnv:
        - name: MINIO_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: tempo-minio-secret
              key: MINIO_ACCESS_KEY_ID
        - name: MINIO_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: tempo-minio-secret
              key: MINIO_SECRET_ACCESS_KEY
      nodeSelector:
        kubernetes.io/arch: arm64

    # Configure querier
    querier:
      # Enable environment variables in config file
      extraArgs:
        - '-config.expand-env=true'
      extraEnv:
        - name: MINIO_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: tempo-minio-secret
              key: MINIO_ACCESS_KEY_ID
        - name: MINIO_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: tempo-minio-secret
              key: MINIO_SECRET_ACCESS_KEY
      nodeSelector:
        kubernetes.io/arch: arm64

    # Configure query-frontend
    queryFrontend:
      # Enable environment variables in config file
      extraArgs:
        - '-config.expand-env=true'
      extraEnv:
        - name: MINIO_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: tempo-minio-secret
              key: MINIO_ACCESS_KEY_ID
        - name: MINIO_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: tempo-minio-secret
              key: MINIO_SECRET_ACCESS_KEY
      nodeSelector:
        kubernetes.io/arch: arm64

    # Disable Minio server installation
    minio:
      enabled: false

    # ✅ ServiceMonitor
    serviceMonitor:
      enabled: true
      labels:
        release: prometheus