apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tempo
  namespace: tempo
spec:
  interval: 5m
  chart:
    spec:
      chart: tempo-distributed
      version: 1.15.2
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: tempo
  values:
    # ✅ Kritisch: Konsistente Ring-Konfiguration
    global:
      ring:
        replication_factor: 1
    
    # ✅ Alle Komponenten mit gleicher Replikas-Anzahl
    distributor:
      replicas: 1
      extraArgs:
        - '-config.expand-env=true'
      extraEnv:
        - name: MINIO_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: tempo-minio-secret
              key: MINIO_ACCESS_KEY_ID
        - name: MINIO_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: tempo-minio-secret
              key: MINIO_SECRET_ACCESS_KEY
    
    ingester:
      replicas: 1
      extraArgs:
        - '-config.expand-env=true'
      extraEnv:
        - name: MINIO_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: tempo-minio-secret
              key: MINIO_ACCESS_KEY_ID
        - name: MINIO_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: tempo-minio-secret
              key: MINIO_SECRET_ACCESS_KEY
    
    compactor:
      replicas: 1
      extraArgs:
        - '-config.expand-env=true'
      extraEnv:
        - name: MINIO_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: tempo-minio-secret
              key: MINIO_ACCESS_KEY_ID
        - name: MINIO_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: tempo-minio-secret
              key: MINIO_SECRET_ACCESS_KEY
    
    querier:
      replicas: 1
      extraArgs:
        - '-config.expand-env=true'
      extraEnv:
        - name: MINIO_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: tempo-minio-secret
              key: MINIO_ACCESS_KEY_ID
        - name: MINIO_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: tempo-minio-secret
              key: MINIO_SECRET_ACCESS_KEY
    
    queryFrontend:
      replicas: 1
      extraArgs:
        - '-config.expand-env=true'
      extraEnv:
        - name: MINIO_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: tempo-minio-secret
              key: MINIO_ACCESS_KEY_ID
        - name: MINIO_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: tempo-minio-secret
              key: MINIO_SECRET_ACCESS_KEY
    
    # ✅ Trace-Protokolle aktivieren
    traces:
      otlp:
        grpc:
          enabled: true
        http:
          enabled: true
    
    # ✅ S3-Storage
    storage:
      trace:
        backend: s3
        s3:
          bucket: k3s-tempo
          endpoint: minio.minio.svc.cluster.local:9000
          region: eu-west-1
          access_key: ${MINIO_ACCESS_KEY_ID}
          secret_key: ${MINIO_SECRET_ACCESS_KEY}
          insecure: true
    
    # ✅ Minio nicht installieren (du hast dein eigenes)
    minio:
      enabled: false
    
    # ✅ ARM64 Support
    nodeSelector:
      kubernetes.io/arch: arm64
    
    # ✅ ServiceMonitor für Prometheus
    serviceMonitor:
      enabled: true
      labels:
        release: prometheus