apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tempo
  namespace: tempo
spec:
  interval: 5m
  chart:
    spec:
      chart: tempo-distributed
      version: 1.15.2
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: tempo
  values:
    # ✅ Explizite Tempo-Konfiguration für Ring
    config: |
      # Memberlist für Ring-Bildung
      memberlist:
        node_name: {{ .Env.HOSTNAME }}
        bind_port: 7946
        join_members:
          - tempo-gossip-ring.tempo.svc.cluster.local:7946
      
      # Distributor Ring
      distributor:
        ring:
          kvstore:
            store: memberlist
          heartbeat_period: 5s
          heartbeat_timeout: 1m
          instance_id: {{ .Env.HOSTNAME }}
          
      # Ingester Ring
      ingester:
        lifecycler:
          ring:
            kvstore:
              store: memberlist
            replication_factor: 3  # ✅ Für 3 Nodes
            heartbeat_period: 5s
            heartbeat_timeout: 1m
            instance_id: {{ .Env.HOSTNAME }}
            num_tokens: 128
          max_transfer_retries: 0
          
      # Compactor Ring
      compactor:
        ring:
          kvstore:
            store: memberlist
          heartbeat_period: 5s
          heartbeat_timeout: 1m
          instance_id: {{ .Env.HOSTNAME }}
      
      # Storage
      storage:
        trace:
          backend: s3
          s3:
            bucket: k3s-tempo
            endpoint: minio.minio.svc.cluster.local:9000
            region: eu-west-1
            access_key: ${MINIO_ACCESS_KEY_ID}
            secret_key: ${MINIO_SECRET_ACCESS_KEY}
            insecure: true

    # ✅ Traces aktivieren
    traces:
      otlp:
        grpc:
          enabled: true
        http:
          enabled: true
      zipkin:
        enabled: true
      jaeger:
        thriftCompact:
          enabled: true
        thriftHttp:
          enabled: true
      opencensus:
        enabled: true

    # ✅ Gossip Ring Service
    gossipRing:
      enabled: true

    # ✅ Distributor (verteilt auf alle Nodes)
    distributor:
      replicas: 3
      extraArgs:
        - '-config.expand-env=true'
      extraEnv:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MINIO_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: tempo-minio-secret
              key: MINIO_ACCESS_KEY_ID
        - name: MINIO_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: tempo-minio-secret
              key: MINIO_SECRET_ACCESS_KEY
      nodeSelector:
        kubernetes.io/arch: arm64

    # ✅ Ingester (verteilt auf alle Nodes)
    ingester:
      replicas: 3
      extraArgs:
        - '-config.expand-env=true'
      extraEnv:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MINIO_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: tempo-minio-secret
              key: MINIO_ACCESS_KEY_ID
        - name: MINIO_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: tempo-minio-secret
              key: MINIO_SECRET_ACCESS_KEY
      nodeSelector:
        kubernetes.io/arch: arm64

    # ✅ Compactor (1 Replik reicht)
    compactor:
      replicas: 1
      extraArgs:
        - '-config.expand-env=true'
      extraEnv:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MINIO_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: tempo-minio-secret
              key: MINIO_ACCESS_KEY_ID
        - name: MINIO_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: tempo-minio-secret
              key: MINIO_SECRET_ACCESS_KEY
      nodeSelector:
        kubernetes.io/arch: arm64

    # ✅ Querier (verteilt auf alle Nodes)
    querier:
      replicas: 3
      extraArgs:
        - '-config.expand-env=true'
      extraEnv:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MINIO_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: tempo-minio-secret
              key: MINIO_ACCESS_KEY_ID
        - name: MINIO_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: tempo-minio-secret
              key: MINIO_SECRET_ACCESS_KEY
      nodeSelector:
        kubernetes.io/arch: arm64

    # ✅ Query Frontend (Load Balancer)
    queryFrontend:
      replicas: 2
      extraArgs:
        - '-config.expand-env=true'
      extraEnv:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MINIO_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: tempo-minio-secret
              key: MINIO_ACCESS_KEY_ID
        - name: MINIO_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: tempo-minio-secret
              key: MINIO_SECRET_ACCESS_KEY
      nodeSelector:
        kubernetes.io/arch: arm64

    # ✅ Minio deaktivieren
    minio:
      enabled: false

    # ✅ ServiceMonitor für Prometheus
    serviceMonitor:
      enabled: true
      labels:
        release: prometheus