apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tempo
  namespace: tempo
spec:
  interval: 5m
  chart:
    spec:
      chart: tempo-distributed
      version: 1.15.2
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: tempo
  values:
    # ✅ Einfache Trace-Konfiguration
    traces:
      otlp:
        grpc:
          enabled: true
        http:
          enabled: true
      zipkin:
        enabled: true
      jaeger:
        thriftCompact:
          enabled: true
        thriftHttp:
          enabled: true
      opencensus:
        enabled: true

    # ✅ S3 Storage mit Umgebungsvariablen
    storage:
      trace:
        backend: s3
        s3:
          bucket: k3s-tempo
          endpoint: minio.minio.svc.cluster.local:9000
          region: eu-west-1
          access_key: ${MINIO_ACCESS_KEY_ID}
          secret_key: ${MINIO_SECRET_ACCESS_KEY}
          insecure: true

    # ✅ Distributor mit Environment-Variablen
    distributor:
      replicas: 1
      config:
        log_received_spans:
          enabled: true
      extraArgs:
        - '-config.expand-env=true'
      extraEnv:
        - name: MINIO_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: tempo-minio-secret
              key: MINIO_ACCESS_KEY_ID
        - name: MINIO_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: tempo-minio-secret
              key: MINIO_SECRET_ACCESS_KEY
      nodeSelector:
        kubernetes.io/arch: arm64

    # ✅ Ingester mit Environment-Variablen
    ingester:
      replicas: 1
      extraArgs:
        - '-config.expand-env=true'
      extraEnv:
        - name: MINIO_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: tempo-minio-secret
              key: MINIO_ACCESS_KEY_ID
        - name: MINIO_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: tempo-minio-secret
              key: MINIO_SECRET_ACCESS_KEY
      nodeSelector:
        kubernetes.io/arch: arm64

    # ✅ Compactor mit Environment-Variablen
    compactor:
      replicas: 1
      extraArgs:
        - '-config.expand-env=true'
      extraEnv:
        - name: MINIO_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: tempo-minio-secret
              key: MINIO_ACCESS_KEY_ID
        - name: MINIO_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: tempo-minio-secret
              key: MINIO_SECRET_ACCESS_KEY
      nodeSelector:
        kubernetes.io/arch: arm64

    # ✅ Querier mit Environment-Variablen
    querier:
      replicas: 1
      extraArgs:
        - '-config.expand-env=true'
      extraEnv:
        - name: MINIO_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: tempo-minio-secret
              key: MINIO_ACCESS_KEY_ID
        - name: MINIO_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: tempo-minio-secret
              key: MINIO_SECRET_ACCESS_KEY
      nodeSelector:
        kubernetes.io/arch: arm64

    # ✅ Query Frontend mit Environment-Variablen
    queryFrontend:
      replicas: 1
      extraArgs:
        - '-config.expand-env=true'
      extraEnv:
        - name: MINIO_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: tempo-minio-secret
              key: MINIO_ACCESS_KEY_ID
        - name: MINIO_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: tempo-minio-secret
              key: MINIO_SECRET_ACCESS_KEY
      nodeSelector:
        kubernetes.io/arch: arm64

    # ✅ Minio deaktivieren
    minio:
      enabled: false

    # ✅ ServiceMonitor für Prometheus
    serviceMonitor:
      enabled: true
      labels:
        release: prometheus