apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tempo
  namespace: tempo
spec:
  interval: 5m
  chart:
    spec:
      chart: tempo-distributed
      version: 1.15.2
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: tempo
  values:
    # ✅ WICHTIG: Globale Konfiguration für Single-Node-Cluster
    global:
      extraArgs:
        - '-config.expand-env=true'
      extraEnv:
        - name: MINIO_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: tempo-minio-secret
              key: MINIO_ACCESS_KEY_ID
        - name: MINIO_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: tempo-minio-secret
              key: MINIO_SECRET_ACCESS_KEY
    
    # ✅ Enable trace ingestion
    traces:
      otlp:
        grpc:
          enabled: true
        http:
          enabled: true
      zipkin:
        enabled: true
      jaeger:
        thriftCompact:
          enabled: true
        thriftHttp:
          enabled: true
      opencensus:
        enabled: true
    
    # ✅ Configure S3 backend
    storage:
      trace:
        backend: s3
        s3:
          bucket: k3s-tempo
          endpoint: minio.minio.svc.cluster.local:9000
          region: eu-west-1
          access_key: ${MINIO_ACCESS_KEY_ID}
          secret_key: ${MINIO_SECRET_ACCESS_KEY}
          insecure: true
          forcepathstyle: true  # ✅ Wichtig für Minio
    
    # ✅ Configure distributor
    distributor:
      replicas: 1
      config:
        log_received_spans:
          enabled: true
        ring:
          replication_factor: 1  # ✅ Hier auch setzen
      extraArgs:
        - '-config.expand-env=true'
      extraEnv:
        - name: MINIO_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: tempo-minio-secret
              key: MINIO_ACCESS_KEY_ID
        - name: MINIO_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: tempo-minio-secret
              key: MINIO_SECRET_ACCESS_KEY
      resources:
        limits:
          memory: 512Mi
          cpu: 200m
        requests:
          memory: 256Mi
          cpu: 100m
    
    # ✅ Configure ingester - WICHTIGSTE ÄNDERUNG
    ingester:
      replicas: 1
      config:
        lifecycler:
          ring:
            replication_factor: 1  # ✅ Schon da
            kvstore:
              store: memberlist
          num_tokens: 128
          heartbeat_timeout: 1m
          join_after: 30s
          min_ready_duration: 15s
          final_sleep: 30s
        # ✅ WICHTIG: Zusätzliche Konfiguration für Single-Node
        complete_block_timeout: 1m
        max_block_duration: 30m
        max_block_bytes: 1000000
        flush_all_on_shutdown: true
      extraArgs:
        - '-config.expand-env=true'
      extraEnv:
        - name: MINIO_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: tempo-minio-secret
              key: MINIO_ACCESS_KEY_ID
        - name: MINIO_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: tempo-minio-secret
              key: MINIO_SECRET_ACCESS_KEY
      resources:
        limits:
          memory: 512Mi
          cpu: 200m
        requests:
          memory: 256Mi
          cpu: 100m
    
    # ✅ Configure compactor
    compactor:
      replicas: 1
      config:
        ring:
          replication_factor: 1  # ✅ Hier auch setzen
      extraArgs:
        - '-config.expand-env=true'
      extraEnv:
        - name: MINIO_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: tempo-minio-secret
              key: MINIO_ACCESS_KEY_ID
        - name: MINIO_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: tempo-minio-secret
              key: MINIO_SECRET_ACCESS_KEY
      resources:
        limits:
          memory: 512Mi
          cpu: 200m
        requests:
          memory: 256Mi
          cpu: 100m
    
    # ✅ Configure querier
    querier:
      replicas: 1
      config:
        ring:
          replication_factor: 1  # ✅ Hier auch setzen
      extraArgs:
        - '-config.expand-env=true'
      extraEnv:
        - name: MINIO_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: tempo-minio-secret
              key: MINIO_ACCESS_KEY_ID
        - name: MINIO_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: tempo-minio-secret
              key: MINIO_SECRET_ACCESS_KEY
      resources:
        limits:
          memory: 512Mi
          cpu: 200m
        requests:
          memory: 256Mi
          cpu: 100m
    
    # ✅ Configure query-frontend
    queryFrontend:
      replicas: 1
      extraArgs:
        - '-config.expand-env=true'
      extraEnv:
        - name: MINIO_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: tempo-minio-secret
              key: MINIO_ACCESS_KEY_ID
        - name: MINIO_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: tempo-minio-secret
              key: MINIO_SECRET_ACCESS_KEY
      resources:
        limits:
          memory: 512Mi
          cpu: 200m
        requests:
          memory: 256Mi
          cpu: 100m
    
    # ✅ Disable Minio server installation
    minio:
      enabled: false
    
    # ✅ ARM64 Node Selection
    nodeSelector:
      kubernetes.io/arch: arm64
    
    # ✅ Service Monitor für Prometheus
    serviceMonitor:
      enabled: true
      labels:
        release: prometheus