apiVersion: v1
kind: Secret
metadata:
  name: tempo-minio-secret
  namespace: tempo
type: Opaque
data:
  MINIO_ACCESS_KEY_ID: dGVtcG8=  # base64 "tempo"
  MINIO_SECRET_ACCESS_KEY: dGVtcG9QYXNzd29yZA==  # base64 "tempoPassword"