apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  values:
    grafana:
      service:
        type: ClusterIP
        port: 80
        targetPort: 3000
