apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "66.2.2"

      # version: "66.x (latest)"
      # alternativ: flux updatet es automatisch prometheus und grafana, weil das repo sehr lebendig ist
      # opder 6.5.*

      sourceRef:
        kind: HelmRepository
        name: kube-prometheus-stack
        namespace: monitoring
      interval: 12h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  driftDetection:
    mode: enabled
    ignore:
      # Ignore "validated" annotation which is not inserted during install
      - paths: ["/metadata/annotations/prometheus-operator-validated"]
        target:
          kind: PrometheusRule
  values:
    grafana:
      adminPassword: timour
    ingress:
      ## If true, Grafana Ingress will be created
      enabled: true

      ## IngressClassName for Grafana Ingress.
      ## Should be provided if Ingress is enable.
      ingressClassName: traefik

      ## Annotations for Grafana Ingress
      annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"

      ## Labels to be added to the Ingress
      labels: {}

      ## Hostnames.
      ## Must be provided if Ingress is enable.
      hosts:
        - grafana.timourhomelab.org
      #  hosts: []

      ## Path for Grafana ingress (optional - uncomment if needed)
      # path: /

      ## TLS configuration for Grafana Ingress
      ## Secret must be manually created in the namespace
      tls: []
      # vorerst empty
      # - secretName: grafana-general-tls
      #   hosts:
      #     - grafana.example.com
