apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "66.2.2"
      sourceRef:
        kind: HelmRepository
        name: kube-prometheus-stack
        namespace: monitoring
      interval: 12h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  driftDetection:
    mode: enabled
    ignore:
      - paths: ["/metadata/annotations/prometheus-operator-validated"]
        target:
          kind: PrometheusRule
  values:
    # Alle Komponenten dieses Charts (Prometheus, Grafana, Alertmanager etc.) werden auf p3 geplant
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - p3

    grafana:
      adminPassword: timour

      # ✅ NUR die Data Sources hinzufügen (Rest bleibt gleich)
      additionalDataSources:
        - name: Tempo
          type: tempo
          uid: tempo
          access: proxy
          url: http://tempo-query-frontend.tempo.svc.cluster.local:3100
          jsonData:
            httpMethod: GET
            serviceMap:
              datasourceUid: prometheus
        - name: Loki
          type: loki
          uid: loki
          access: proxy
          url: http://loki.monitoring.svc.cluster.local:3100
          jsonData:
            # ✅ Trace-zu-Log-Korrelation (das ist der Mehrwert!)
            derivedFields:
              - datasourceUid: tempo
                matcherRegex: '"trace_id":"([^"]*)"'
                name: TraceID
                url: '$${__value.raw}'

      ingress:
        enabled: true
        ingressClassName: traefik
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
        labels: {}
        hosts:
          - grafana.timourhomelab.org
        tls:
          - secretName: grafana-tls-secret
            hosts:
              - grafana.timourhomelab.org

    # ✅ Alertmanager-Konfiguration
    alertmanager:
      alertmanagerSpec:
        nodeSelector:
          kubernetes.io/hostname: p3