apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkding
  namespace: linkding
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkding
  template:
    metadata:
      labels:
        app: linkding
    spec:
      securityContext:
        fsGroup: 33 # www-data group ID
        runAsUser: 33 # www-data user ID
        runAsGroup: 33 # www-data group ID
      containers:
        - name: linkding
          image: sissbruecker/linkding:1.37.0
          env:
            - name: LD_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: linkding-database-cluster-app
                  key: password
            - name: LD_DB_USER
              valueFrom:
                secretKeyRef:
                  name: linkding-database-cluster-app
                  key: user
          envFrom:
            - secretRef:
                name: linkding-superuser
            - configMapRef:
                name: linkding-configmap
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: linkding-data
              mountPath: /etc/linkding/data
          securityContext:
            allowPrivilegeEscalation: false
      volumes:
        - name: linkding-data
          persistentVolumeClaim:
            claimName: linkding-data-pvc
