# apps/base/immich/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-config
  namespace: immich
data:
  # Database settings
  DB_HOSTNAME: "immich-db-rw.immich"
  DB_DATABASE_NAME: "immich"
  DB_USERNAME: "immich"
  DB_PORT: "5432"
  
  # Redis settings
  REDIS_HOSTNAME: "immich-redis-master.immich.svc.cluster.local"
  REDIS_PORT: "6379"
  REDIS_DBINDEX: "0"
  
  # Immich settings
  NODE_ENV: "production"
  LOG_LEVEL: "info"
  IMMICH_MACHINE_LEARNING_URL: "http://immich-ml:3003"
  IMMICH_MEDIA_LOCATION: "/usr/src/app/upload"
  IMMICH_MICROSERVICES_URL: "http://immich-microservices:3002"
  UPLOAD_LOCATION: "/usr/src/app/upload"
  
  # ML settings
  MACHINE_LEARNING_CACHE_FOLDER: "/cache"
  MACHINE_LEARNING_WORKER_COUNT: "1"