# apps/base/immich/db-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: immich-db-secret
  namespace: immich
type: Opaque
data:
  # The base64 encoded password from the PostgreSQL deployment
  password: WTNxc3FFeHNUbDhZekt6a0pmaXlJNzJ0dVNoN2pjSm5JOGxWUjVCQmVvdTRqMGZsa21PUXZKKKHZ1NnBBbWti