# debug-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: immich-debug
  namespace: immich
spec:
  containers:
  - name: debug
    image: ghcr.io/immich-app/immich-server:v1.135.3
    command: ["/bin/sh", "-c", "sleep 3600"]
    env:
    - name: DB_HOSTNAME
      value: "immich-db-rw.immich"
    - name: DB_DATABASE_NAME
      value: "immich"
    - name: DB_USERNAME
      value: "immich"
    - name: DB_PASSWORD
      value: "Zpu18ctdeOXzmttsByhPVN7IuiknLTw4r8uQdYVpJThewXv82TV6drcRP7M2jpZz" 
    - name: DB_PORT
      value: "5432"
    - name: REDIS_HOSTNAME
      value: "immich-redis-master.immich"
    - name: REDIS_PORT
      value: "6379"
    - name: REDIS_PASSWORD
      value: "password"
    - name: NODE_ENV
      value: "production"
    - name: LOG_LEVEL
      value: "log"
    - name: JWT_SECRET
      value: "change-this-to-a-random-string"
    - name: UPLOAD_LOCATION
      value: "/usr/src/app/upload"
    volumeMounts:
    - name: uploads
      mountPath: /usr/src/app/upload
  volumes:
  - name: uploads
    persistentVolumeClaim:
      claimName: immich-uploads-pvc