# apps/base/immich/deployment-ml.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-ml
  namespace: immich
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich-ml
  template:
    metadata:
      labels:
        app: immich-ml
    spec:
      containers:
      - name: immich-ml
        image: ghcr.io/immich-app/immich-machine-learning:v1.93.1
        ports:
        - containerPort: 3003
        volumeMounts:
        - name: model-cache
          mountPath: /cache
        resources:
          limits:
            cpu: 2000m
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 1Gi
      volumes:
      - name: model-cache
        persistentVolumeClaim:
          claimName: immich-ml-cache-pvc