# apps/base/immich/deployment-server.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-server
  namespace: immich
  labels:
    app: immich-server
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: immich-server
  template:
    metadata:
      labels:
        app: immich-server
    spec:
      securityContext:
        fsGroup: 0
      serviceAccountName: default
      dnsPolicy: ClusterFirst
      initContainers:
        - name: postgresql-isready
          image: "postgres:14-alpine"
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: immich-config
                  key: DB_USERNAME
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: immich-config
                  key: DB_DATABASE_NAME
          command:
            - /bin/sh
            - -c
            - until pg_isready -U "${POSTGRES_USER}" -d "dbname=${POSTGRES_DB}" -h immich-db-rw.immich -p 5432; do echo "waiting for database"; sleep 2; done
      containers:
        - name: immich-server
          image: "ghcr.io/immich-app/immich-server:v1.132.3"
          command: ["node", "dist/main.js", "immich"]
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 0
          ports:
            - containerPort: 3001
          env:
            - name: DB_PASSWORD
              value: "Zpu18ctdeOXzmttsByhPVN7IuiknLTw4r8uQdYVpJThewXv82TV6drcRP7M2jpZz"
            - name: REDIS_PASSWORD
              value: "password"
            - name: JWT_SECRET
              value: "change-me-to-a-secure-random-string-123456"
            - name: IMMICH_DISABLE_EXTENSIONS_CHECK
              value: "true"
          envFrom:
            - configMapRef:
                name: immich-config
          livenessProbe:
            failureThreshold: 120
            httpGet:
              path: /server/ping
              port: 3001
            initialDelaySeconds: 60
            periodSeconds: 120
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 120
            httpGet:
              path: /server/ping
              port: 3001
            initialDelaySeconds: 60
            periodSeconds: 120
            timeoutSeconds: 5
          volumeMounts:
            - name: uploads
              mountPath: /usr/src/app/upload
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: immich-uploads-pvc