# immich-debug.yaml
apiVersion: v1
kind: Pod
metadata:
  name: immich-debug
  namespace: immich
spec:
  containers:
  - name: debug
    image: ghcr.io/immich-app/immich-server:v1.93.1
    command: ["/bin/sh", "-c", "sleep 3600"]
    env:
    - name: DB_PASSWORD
      value: "Zpu18ctdeOXzmttsByhPVN7IuiknLTw4r8uQdYVpJThewXv82TV6drcRP7M2jpZz"
    - name: REDIS_PASSWORD
      value: "password"
    - name: JWT_SECRET
      value: "something-random-for-testing-purposes"
    - name: LOG_LEVEL
      value: "log"
    envFrom:
    - configMapRef:
        name: immich-config
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 200m
        memory: 500Mi