# apps/base/immich/services.yaml
apiVersion: v1
kind: Service
metadata:
  name: immich-server
  namespace: immich
spec:
  selector:
    app: immich-server
  ports:
  - port: 80
    targetPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: immich-microservices
  namespace: immich
spec:
  selector:
    app: immich-microservices
  ports:
  - port: 3002
    targetPort: 3002
---
apiVersion: v1
kind: Service
metadata:
  name: immich-ml
  namespace: immich
spec:
  selector:
    app: immich-ml
  ports:
  - port: 3003
    targetPort: 3003