apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: hubble-ui
  namespace: kube-system
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`hubble.cluster.local`) || Path(`/hubble`)
      kind: Rule
      services:
        - name: hubble-ui
          port: 80
