apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  name: default
  namespace: velero
spec:
  provider: aws
  objectStorage:
    bucket: piclusterhomelab-velero
  credential:
    name: aws-credentials
    key: cloud
  config:
    region: eu-central-1
