apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  values:
    # Enable CSI features properly
    features: EnableCSI
    
    # Configure backup locations
    configuration:
      provider: aws
      backupStorageLocation:
        name: default
        bucket: piclusterhomelab-velero
        prefix: backups
        config:
          region: eu-central-1
      volumeSnapshotLocation:
        name: aws
        config:
          region: eu-central-1
      # Add these parameters to fix backup issues
      restoreResourcePriorities: namespaces,persistentvolumes,persistentvolumeclaims,secrets,configmaps
      kubeAPIQPS: 20
      kubeAPIBurst: 30
      backupSyncPeriod: 1m
    
    # Add the specific CSI plugin setup
    initContainers:
      - name: velero-plugin-for-csi
        image: velero/velero-plugin-for-csi:v0.6.0
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins
    
    # Update pod annotations to force restart
    podAnnotations:
      timestamp: "2025-05-21-10-56"