apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  values:
    image:
      repository: velero/velero
      tag: v1.12.0  # ARM64-compatible version
    
    # Enable CSI features
    features: EnableCSI
    
    # CSI integration
    extraEnvVars:
      - name: VELERO_FEATURES
        value: "EnableCSI"
      - name: VELERO_DISABLE_API_GROUP_VERSIONS_CHECK
        value: "true"
    
    # Resources suitable for Pi
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi