apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  values:
    credentials:
      useSecret: true
      name: cloud-credentials  # Name des Volumes innerhalb des Pods
      secretName: velero-aws-credentials  # Name des Kubernetes Secrets
    
    configuration:
      provider: aws
      backupStorageLocation:
        name: default
        bucket: piclusterhomelab-velero
        prefix: backups
        config:
          region: eu-central-1
      defaultVolumesToFsBackup: true  # File-basierte Backups
    
    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.8.0
        volumeMounts:
          - mountPath: /target
            name: plugins
