apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: velero-ui-ingress
  namespace: velero
  annotations:
    kubernetes.io/ingress.class: traefik
    # Wichtig für Backend-Verbindung
    traefik.ingress.kubernetes.io/service-weights: "velero-ui:100"
spec:
  rules:
  - host: velero.timourhomelab.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: velero-ui
            port:
              number: 3000