apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: velero-ui
  namespace: velero
spec:
  ingressClassName: traefik # Changed to traefik
  #  tls:
  #   - hosts:
  #      - velero.timourhomelab.com
  #    secretName: velero-tls
  rules:
    - host: velero.timourhomelab.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: velero-ui
                port:
                  number: 80
