apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/velero
  - ingress.yaml
  - velero-ui.yaml
  - serviceaccount.yaml
  - velero-ui-credentials.yaml 
  - csi-snapshot-controller.yaml 
