apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/velero
  - velero-ui.yaml
  - velero-ui-credentials.yaml
  - ingress.yaml
  - serviceaccount.yaml
patchesStrategicMerge:
  - helmrelease-patch.yaml