apiVersion: v1
kind: ServiceAccount
metadata:
  name: velero-ui
  namespace: velero
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: velero-ui-reader
rules:
  - apiGroups: [""]
    resources:
      [
        "pods",
        "namespaces",
        "services",
        "persistentvolumes",
        "persistentvolumeclaims",
        "nodes",
      ]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["velero.io"]
    resources:
      [
        "backups",
        "restores",
        "schedules",
        "backupstoragelocations",
        "deletebackuprequests",
      ]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: velero-ui-reader-binding
subjects:
  - kind: ServiceAccount
    name: velero-ui
    namespace: velero
roleRef:
  kind: ClusterRole
  name: velero-ui-reader
  apiGroup: rbac.authorization.k8s.io
