apiVersion: apps/v1
kind: Deployment
metadata:
  name: velero-ui
  namespace: velero
spec:
  replicas: 1
  selector:
    matchLabels:
      app: velero-ui
  template:
    metadata:
      labels:
        app: velero-ui
    spec:
      serviceAccountName: velero-ui # Add this line to use the ServiceAccount
      containers:
        - name: velero-ui
          image: otwld/velero-ui:0.5.2
          ports:
            - containerPort: 8080
          env:
            - name: VELERO_API_URL
              value: "http://velero.velero.svc:8085"
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
      nodeSelector:
        kubernetes.io/hostname: p3
---
apiVersion: v1
kind: Service
metadata:
  name: velero-ui
  namespace: velero
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080 # Default port for the UI
  selector:
    app: velero-ui
