apiVersion: apps/v1
kind: Deployment
metadata:
  name: velero-ui
  namespace: velero
spec:
  replicas: 1
  selector:
    matchLabels:
      app: velero-ui
  template:
    metadata:
      labels:
        app: velero-ui
    spec:
      containers:
        - name: velero-ui
          # Use dragondrop-cloud/velero-ui image
          image: dragondropcloud/velero-ui:latest
          ports:
            - containerPort: 80 # This UI listens on port 80
          env:
            # This UI might use different env vars, check its documentation if needed
            # For now, let's assume it auto-discovers or doesn't need explicit API URL
            # - name: API_URL
            #   value: "http://velero.velero.svc:8085"
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
      nodeSelector:
        kubernetes.io/hostname: p3 # Keep targeting your p3 node
---
apiVersion: v1
kind: Service
metadata:
  name: velero-ui
  namespace: velero
spec:
  ports:
    - name: http # Add a name for clarity
      port: 80
      targetPort: 80 # Match the containerPort
  selector:
    app: velero-ui
