apiVersion: apps/v1
kind: Deployment
metadata:
  name: velero-ui
  namespace: velero
spec:
  replicas: 1
  selector:
    matchLabels:
      app: velero-ui
  template:
    metadata:
      labels:
        app: velero-ui
    spec:
      serviceAccountName: velero-ui
      containers:
      - name: velero-ui
        image: otwld/velero-ui:0.7.0
        ports:
        - containerPort: 8080  # Auf 8080 ändern - das ist der tatsächliche Port
        env:
        - name: VELERO_NAMESPACE
          value: velero
        - name: ADMIN_USERNAME
          valueFrom:
            secretKeyRef:
              name: velero-ui-credentials
              key: ADMIN_USERNAME
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: velero-ui-credentials
              key: ADMIN_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: velero-ui
  namespace: velero
spec:
  selector:
    app: velero-ui
  ports:
  - port: 80
    targetPort: 8080  # Auf 8080 ändern, um mit dem tatsächlichen Port übereinzustimmen