apiVersion: apps/v1
kind: Deployment
metadata:
  name: velero-ui
  namespace: velero
spec:
  replicas: 1
  selector:
    matchLabels:
      app: velero-ui
  template:
    metadata:
      labels:
        app: velero-ui
    spec:
      containers:
        - name: velero-ui
          # Use weaviate/velero-ui with the specific tag v0.2.4
          image: weaviate/velero-ui:0.2.4
          ports:
            - containerPort: 8080 # Default port for this UI
          env:
            # Point the UI to the Velero service API
            - name: VELERO_API_URL
              value: "http://velero.velero.svc:8085"
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
      nodeSelector:
        kubernetes.io/hostname: p3 # Target your specific node
---
# --- (if putting in the same file as the Deployment)
apiVersion: v1
kind: Service
metadata:
  name: velero-ui
  namespace: velero
spec:
  ports:
    - name: http
      port: 80 # Port the service will listen on
      targetPort: 8080 # Port the container listens on (8080 for this UI)
  selector:
    app: velero-ui # Selects the pods created by the Deployment
