apiVersion: apps/v1
kind: Deployment
metadata:
  name: velero-ui
  namespace: velero
spec:
  replicas: 1
  selector:
    matchLabels:
      app: velero-ui
  template:
    metadata:
      labels:
        app: velero-ui
    spec:
      serviceAccountName: velero-ui
      containers:
        - name: velero-ui
          image: otwld/velero-ui:0.5.2
          ports:
            - containerPort: 8080
          env:
            - name: VELERO_API_URL
              value: "http://velero.velero.svc:8085"
            # Add environment variables from the secret
            - name: ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: velero-ui-credentials
                  key: ADMIN_USERNAME
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: velero-ui-credentials
                  key: ADMIN_PASSWORD
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
      nodeSelector:
        kubernetes.io/hostname: p3
        ## standart pw : admin user:admin
---
apiVersion: v1
kind: Service
metadata:
  name: velero-ui
  namespace: velero
spec:
  ports:
    - name: http
      port: 80
      targetPort: 3000 # Default port for the UI
  selector:
    app: velero-ui
