apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: velero-ui-credentials
  namespace: velero
  annotations:
    force-sync: "true"
    reconcile.external-secrets.io/verbose-logging: "true"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: velero-ui-credentials
    creationPolicy: Owner
  data:
    - secretKey: ADMIN_USERNAME
      remoteRef:
        key: picluster/velero-ui-credentials
        property: username
    - secretKey: ADMIN_PASSWORD
      remoteRef:
        key: picluster/velero-ui-credentials
        property: password
