apiVersion: apps/v1
kind: Deployment
metadata:
  name: velero-ui
  namespace: velero
spec:
  replicas: 1
  selector:
    matchLabels:
      app: velero-ui
  template:
    metadata:
      labels:
        app: velero-ui
    spec:
      containers:
        - name: velero-ui
          # Use komodorio/velero-ui image
          image: komodorio/velero-ui:latest # Changed image
          ports:
            - containerPort: 8080 # This UI listens on port 8080 by default
          env:
            # Point the UI to the Velero service
            - name: VELERO_API_URL
              value: "http://velero.velero.svc:8085"
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
      nodeSelector:
        kubernetes.io/hostname: p3 # Keep targeting your p3 node
---
apiVersion: v1
kind: Service
metadata:
  name: velero-ui
  namespace: velero
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080 # Match the containerPort (8080 for komodorio/velero-ui)
  selector:
    app: velero-ui
